apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: elastic
spec:
  acme:
    # Staging API
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: glenn@latomme.org
    privateKeySecretRef:
      name: account-key-staging
    solvers:
    - selector: {}
      http01:
       ingress:
         class: nginx