replicaCount: 1
image:
  useImagePullSecrets: true
  pullPolicy: Always
  repository: ghcr.io/badminton-apps/core/import

service:
  name: badman-import
  internalPort: 4001
  externalPort: 80

controller:
  podAnnotations:
    co.elastic.logs/json.keys_under_root: true
    co.elastic.logs/json.overwrite_keys: true
    co.elastic.logs/json.add_error_key: true
    co.elastic.logs/json.expand_keys: true

database:
  DB_IP: server-postgresql.badvla
  DB_DATABASE: ranking
  DB_USER: postgres
  DB_DIALECT: postgres


auth0:
  issuer: https://badvlasim.eu.auth0.com

apm:
  server: http://elastic-apm-apm-http.elastic:8200

esc:
  server: http://elastic-search-es-http.elastic:9200