
backend:
  - backend/**/*
frontend:
  - frontend/**/*

'@badvlasim/shared':
  - backend/packages/_shared
'@badvlasim/import':
  - backend/packages/import
'@badvlasim/server':
  - backend/packages/_shared
'@badvlasim/simulate':
  - backend/packages/simulate
'@badvlasim/client':
  - frontend/packages/ranking-client

database:
  - ./**/*.sql

documentation:
  - any: ['./**/*.md', '!./**/changelog.md']