backend:
  - code/backend/*
  - code/backend/**/*
frontend:
  - code/frontend/*
  - code/frontend/**/*

'@badvlasim/shared':
  - code/backend/packages/_shared/*
  - code/backend/packages/_shared/**/*
'@badvlasim/import':
  - code/backend/packages/import/*
  - code/backend/packages/import/**/*
'@badvlasim/server':
  - code/backend/packages/server/*
  - code/backend/packages/server/**/*
'@badvlasim/simulate':
  - code/backend/packages/simulate/*
  - code/backend/packages/simulate/**/*
'@badvlasim/client':
  - code/frontend/packages/client/*
  - code/frontend/packages/client/**/*

database:
  - ./**/*.sql

documentation:
  - any: ['./**/*.md', '!./**/changelog.md']
