version: '3'
services:

  # My Apps
  badman:
    image: badman/client
    environment:
      - API_URL=http://api:5000
      - CHOKIDAR_USEPOLLING=true
    expose:
      - 4200
    ports:
      - 4200:4200
    depends_on:
      - api
    volumes:
      - ./:/usr/src
      - ./user/src/node_modules
    restart: unless-stopped

  api:
    image: badamn/api
    ports:
      - '5000:5000'
      - '9229:9229'
    networks:
      - api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_IP=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_DIALECT=${DB_DIALECT}
      - APM_SERVER_URL=${APM_SERVER_URL}
      - APM_SERVER_TOKEN=${APM_SERVER_TOKEN}
      - APM_SERVER_ACTIVE=${APM_SERVER_ACTIVE}
      - AUTH0_ISSUER_URL=${AUTH0_ISSUER_URL}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - CLIENT_URL=${CLIENT_URL}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_USER=${MAIL_USER}
      - MAIL_HOST=${MAIL_HOST}
    volumes:
      - ./:/usr/src
      - ./user/src/node_modules
    restart: unless-stopped

networks:
  api:
  postgres:

volumes:
  db-data:
  db-admin:
