apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: badvla-staging
  namespace: badvla
spec:
  dnsNames:
    - badman.app
    - '*.badman.app'
  secretName: badvla-staging-certificate
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
