/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "all": {
        "breakdown": {
            "add-game": {
                "p1t1": string;
                "p1t2": string;
                "p2t1": string;
                "p2t2": string;
                "title": string;
                "won": string;
            };
            "corrected": string;
            "date": string;
            "disclaimer": string;
            "downgrade": string;
            "drops-next-period": string;
            "evolution": string;
            "hint": string;
            "ignored": string;
            "includeOutOfScope": string;
            "lostGames": {
                "none": string;
                "one": string;
                "other": string;
            };
            "nextPeriod": string;
            "no-tean": string;
            "noGames": string;
            "notUsed": string;
            "opponent": string;
            "outOfScope": {
                "none": string;
                "one": string;
                "other": string;
            };
            "period": string;
            "points": string;
            "pointsPerGame": string;
            "prevPeriod": string;
            "removed-games": string;
            "team": string;
            "title": string;
            "untill": string;
            "upgrade": string;
            "usedForDowngrade": string;
            "usedForUpgrade": string;
        };
        "button": {
            "all": string;
            "cancel": string;
            "close": string;
            "create": string;
            "delete": string;
            "detail": string;
            "done": string;
            "edit": string;
            "merge-accounts": string;
            "next": string;
            "no": string;
            "none": string;
            "open-in-new-tab": string;
            "prev": string;
            "save": string;
            "save-and-continue": string;
            "set-primary": string;
            "set-ranking-groups": string;
            "submit": string;
            "sync-ranking": string;
            "watch-system": string;
            "yes": string;
        };
        "club": {
            "current": string;
            "end": string;
            "number": string;
            "start": string;
        };
        "competition": {
            "avg-level": string;
            "away": string;
            "change-encounter": {
                "add-date": string;
                "away-comment": string;
                "calendar": {
                    "option": string;
                    "other-games": string;
                    "remaining": string;
                    "removed": string;
                    "requested": string;
                };
                "choose-date": string;
                "choose-encounter": string;
                "choose-team": string;
                "comments": string;
                "dates": string;
                "description": string;
                "disclaimer-submit": string;
                "errors": {
                    "select-one-date": string;
                    "select-one-date-or-comment": string;
                };
                "home-comment": string;
                "not-possible": string;
                "possible": string;
                "requested": string;
                "requested-failed": string;
                "submit": {
                    "description": string;
                    "title": string;
                };
                "title": string;
            };
            "draw": {
                "encounters": string;
                "title": string;
            };
            "enrollment": {
                "assign-team": string;
                "availability": string;
                "base": string;
                "close": string;
                "closed": string;
                "comment-liga": string;
                "comment-nat": string;
                "comment-prov": string;
                "errors": {
                    "base-max": string;
                    "base-min": string;
                    "best-max": string;
                    "best-players": string;
                    "cant-play": string;
                    "no-captain": string;
                    "no-day": string;
                    "no-location": string;
                    "no-prefferd": string;
                    "not-allowed": string;
                    "not-comp": string;
                };
                "exceptions": string;
                "max": string;
                "new-exception": string;
                "new-play-day": string;
                "open": string;
                "play-day": string;
                "player-base": string;
                "players": {
                    "backup": string;
                    "base": string;
                    "regular": string;
                };
                "save-and-continue-tooltip": string;
                "select-club": string;
                "select-events": string;
                "select-location": string;
                "select-teams": string;
                "select-teams-description": string;
                "title": string;
                "transfer-teams": string;
                "transfer-teams-description": string;
            };
            "home": string;
            "last-updated": string;
            "liga": string;
            "load-more": string;
            "national": string;
            "no-more-encounters": string;
            "no-more-games": string;
            "note": string;
            "prov": string;
            "subevent": {
                "max": string;
                "max-base": string;
                "min-base": string;
            };
            "team-assembly": {
                "avg-level": string;
                "captain": string;
                "change-team": string;
                "disclaimer": string;
                "double1": string;
                "double2": string;
                "double3": string;
                "double4": string;
                "download": string;
                "errors": {
                    "already": string;
                    "club-base-other-team": string;
                    "comp-status": string;
                    "none": string;
                    "not-enough-players": string;
                    "player-above-lower": string;
                    "player-gender": string;
                    "player-genders": string;
                    "player-max-double-games": string;
                    "player-max-mix-games": string;
                    "player-max-mixed-games": string;
                    "player-max-single-games": string;
                    "player-min-level": string;
                    "player-order-doubles": string;
                    "player-order-highest": string;
                    "player-order-single": string;
                    "players-above-lower": string;
                    "team-index": string;
                    "team-to-strong": string;
                    "title": string;
                    "to-much": string;
                };
                "info": string;
                "mix1": string;
                "mix2": string;
                "mix3": string;
                "mix4": string;
                "players": {
                    "backup": string;
                    "base": string;
                    "team": string;
                    "title": string;
                };
                "single1": string;
                "single2": string;
                "single3": string;
                "single4": string;
                "substitude": string;
                "team-index": string;
                "team-index-ignored": string;
                "title": string;
                "warnings": {
                    "subtitute-team-index": string;
                };
            };
            "title": string;
            "type": string;
            "vs": string;
            "vs-short": string;
        };
        "days": {
            "friday": string;
            "monday": string;
            "saturday": string;
            "sunday": string;
            "thursday": string;
            "tuesday": string;
            "wednesday": string;
        };
        "event": {
            "last-sync": string;
            "standing": {
                "games": string;
                "lost": string;
                "name": string;
                "played": string;
                "points": string;
                "sets": string;
                "spoiler": string;
                "tied": string;
                "title": string;
                "totalPoints": string;
                "won": string;
            };
            "type": string;
            "types": {
                "competition": string;
                "tournament": string;
            };
            "usedRankingNote": string;
        };
        "evolution": {
            "warning": string;
        };
        "faq": {
            "info": {
                "description": string;
                "title": string;
            };
            "legend": string;
            "overview": {
                "description": string;
                "evolution-1": string;
                "evolution-2": string;
                "game-result": string;
                "levels": string;
                "title": string;
            };
            "points": {
                "table": {
                    "level": string;
                    "points-needed-down": string;
                    "points-needed-up": string;
                    "points-won": string;
                };
                "title": string;
            };
            "ranking": {
                "description": string;
                "title": string;
            };
            "title": string;
            "updates": {
                "description": string;
                "title": string;
            };
        };
        "game": {
            "bye": string;
            "order": {
                "double": string;
                "female": string;
                "male": string;
                "mix": string;
                "mixed": string;
                "single": string;
            };
            "points": string;
            "recent": {
                "title": string;
            };
            "title": string;
            "types": {
                "double": string;
                "female": string;
                "long": {
                    "D": string;
                    "F": string;
                    "M": string;
                    "MX": string;
                    "S": string;
                };
                "male": string;
                "mix": string;
                "mixed": string;
                "short": {
                    "double": string;
                    "female": string;
                    "male": string;
                    "mix": string;
                    "single": string;
                };
                "single": string;
                "title": string;
            };
            "unkown": string;
            "upcoming": {
                "title": string;
            };
        };
        "gender": {
            "female": string;
            "females": string;
            "long": {
                "F": string;
                "M": string;
                "MX": string;
            };
            "male": string;
            "males": string;
            "mix": string;
            "national": string;
            "select": string;
            "short": {
                "female": string;
                "male": string;
                "mix": string;
            };
            "title": string;
        };
        "input": {
            "abbreviation": string;
            "city": string;
            "competitionplayer": string;
            "courts": string;
            "date": string;
            "date-range": string;
            "day": string;
            "email": string;
            "fax": string;
            "firstname": string;
            "fullName": string;
            "gender": string;
            "lastname": string;
            "memberId": string;
            "name": string;
            "phone": string;
            "postalcode": string;
            "required": string;
            "select": string;
            "shuttle": string;
            "state": string;
            "street": string;
            "streetnumber": string;
            "sub": string;
            "this-required": string;
            "type": string;
            "year": string;
        };
        "landing": {
            "description": string;
        };
        "lists": {
            "name": string;
        };
        "loading": string;
        "locations": {
            "title": string;
        };
        "management": {
            "calculate": string;
            "cleanup": string;
            "download": string;
            "end": string;
            "force": string;
            "games-to-use": string;
            "import": string;
            "new-system": string;
            "number-short": string;
            "procent-losing-short": string;
            "procent-winning-short": string;
            "ranking": string;
            "reset": string;
            "select": string;
            "start": string;
            "sync": string;
        };
        "months": {
            "april": string;
            "august": string;
            "december": string;
            "february": string;
            "january": string;
            "june": string;
            "march": string;
            "may": string;
            "november": string;
            "october": string;
            "september": string;
        };
        "notifications": {
            "noNotifications": string;
            "types": {
                "encounterNotAcceptedNotification": string;
                "encounterNotEnteredNotification": string;
            };
        };
        "permission": {
            "no-perm": string;
        };
        "pickers": {
            "end-time": string;
            "select-club": string;
            "select-encounter": string;
            "select-end-time": string;
            "select-start-time": string;
            "select-team": string;
            "select-team-groups": {
                "F": string;
                "M": string;
                "MX": string;
                "NATIONAL": string;
            };
            "select-year": string;
            "start-time": string;
        };
        "players": {
            "backup": string;
            "base": string;
            "no-memberid": string;
            "regular": string;
            "search": {
                "create": string;
                "label": string;
                "not-found": string;
            };
            "title": string;
        };
        "points": {
            "title": string;
        };
        "ranking": {
            "add-ranking": string;
            "all-ranking": string;
            "double": string;
            "double-points": string;
            "double-rank": string;
            "inactive": {
                "double": string;
                "mix": string;
                "single": string;
            };
            "last-ranking": string;
            "last-update": string;
            "list": string;
            "may-ranking": string;
            "mix": string;
            "mix-points": string;
            "mix-rank": string;
            "next-ranking": string;
            "single": string;
            "single-points": string;
            "single-rank": string;
            "trending_down": string;
            "trending_up": string;
            "update-happend": string;
            "updates": string;
            "upload": {
                "comp-status": string;
                "description": string;
                "hint": string;
                "preview": string;
                "ranking-date": string;
                "remove-current-ranking": string;
                "title": string;
                "update-ranking": string;
            };
        };
        "search": {
            "placeholder": string;
            "type": {
                "club": string;
                "eventcompetition": string;
                "eventtournament": string;
                "player": string;
            };
        };
        "settings": {
            "general": {
                "title": string;
            };
            "languages": {
                "en": string;
                "fr_BE": string;
                "nl_BE": string;
                "title": string;
            };
            "notifications": {
                "disclaimer": string;
                "encounter": {
                    "notAcceptedNotification": string;
                    "notEnteredNotification": string;
                    "title": string;
                };
                "encounterChange": {
                    "conformationNotification": string;
                    "finishedNotification": string;
                    "newNotification": string;
                    "title": string;
                };
                "messages": {
                    "encounterNotAcceptedNotification": string;
                    "encounterNotEnteredNotification": string;
                    "syncFailedNotification": string;
                    "syncSuccessNotification": string;
                };
                "sync": {
                    "failed": string;
                    "success": string;
                    "title": string;
                };
                "title": string;
                "types": {
                    "email": string;
                    "none": string;
                    "push": string;
                    "sms": string;
                };
            };
            "title": string;
        };
        "shell": {
            "sidebar": {
                "competition": {
                    "assembly": string;
                    "enrollment": string;
                    "overview": string;
                    "title": string;
                };
                "general": {
                    "changelog": string;
                    "faq": string;
                    "title": string;
                };
                "persnal": {
                    "club": string;
                    "games": string;
                };
                "ranking": {
                    "title": string;
                };
                "tournament": {
                    "title": string;
                };
            };
        };
        "team": {
            "change-number": {
                "description": string;
                "number": string;
                "title": string;
                "tooltip": string;
            };
            "check-players": string;
            "edit": string;
            "location": string;
            "no-perm": {
                "email-phone": string;
            };
            "title": {
                "base-fields": string;
                "captain": string;
                "players": string;
                "prefferd-encounter": string;
            };
            "types": {
                "female": string;
                "long": {
                    "F": string;
                    "M": string;
                    "MX": string;
                    "NATIONAL": string;
                };
                "male": string;
                "mix": string;
                "national": string;
                "short": {
                    "female": string;
                    "male": string;
                    "mix": string;
                    "national": string;
                };
            };
            "usedForTeam": {
                "description": string;
                "example": string;
                "select": string;
                "title": string;
            };
        };
        "themes": {
            "dark": string;
            "light": string;
        };
        "tournament": {
            "away": string;
            "draw": {
                "games": string;
                "title": string;
            };
            "enrollment": {
                "close": string;
                "closed": string;
                "open": string;
                "title": string;
            };
            "home": string;
            "last-updated": string;
            "liga": string;
            "load-more": string;
            "note": string;
            "prov": string;
            "subevent": {
                "max": string;
                "max-base": string;
                "min-base": string;
            };
            "title": string;
            "type": string;
            "vs": string;
            "vs-short": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
