/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "all": {
        "button": {
            "add": string;
            "add-comment": string;
            "add-location": string;
            "agree": string;
            "all": string;
            "cancel": string;
            "clone": string;
            "close": string;
            "copy": string;
            "create": string;
            "delete": string;
            "detail": string;
            "done": string;
            "download": string;
            "edit": string;
            "merge-accounts": string;
            "next": string;
            "no": string;
            "none": string;
            "open-in-new-tab": string;
            "prev": string;
            "save": string;
            "save-and-continue": string;
            "set-primary": string;
            "set-ranking-groups": string;
            "submit": string;
            "sync-ranking": string;
            "watch-system": string;
            "yes": string;
        };
        "club": {
            "current": string;
            "delete": {
                "player": {
                    "description": string;
                    "title": string;
                };
                "team": {
                    "description": string;
                    "title": string;
                };
            };
            "encounters": {
                "change-date": string;
                "change-location": string;
                "change-location-note": string;
                "home-games": string;
                "open-requests": string;
            };
            "end": string;
            "membership-types": {
                "loan": string;
                "normal": string;
            };
            "menu": {
                "add-player": string;
                "twizzit": string;
            };
            "new-team": string;
            "number": string;
            "start": string;
            "titles": {
                "encounters": string;
                "matrix": string;
                "players": string;
                "plural": string;
                "single": string;
                "teams": string;
            };
        };
        "competition": {
            "avg-level": string;
            "away": string;
            "change-encounter": {
                "add-date": string;
                "calendar": {
                    "no-space": string;
                    "option": string;
                    "other-games": string;
                    "remaining": string;
                    "removed": string;
                    "requested": string;
                };
                "choose-date": string;
                "choose-encounter": string;
                "choose-location": string;
                "choose-team": string;
                "close-change-request": string;
                "comment": string;
                "comment-added": string;
                "comments": string;
                "dates": string;
                "description": string;
                "disclaimer-submit": string;
                "errors": {
                    "invalid": string;
                    "select-one-date": string;
                    "select-one-date-or-comment": string;
                };
                "not-possible": string;
                "possible": string;
                "re-open": string;
                "requested": string;
                "requested-failed": string;
                "show-not-availible": {
                    "plural": string;
                    "singular": string;
                };
                "submit": {
                    "description": string;
                    "title": string;
                };
                "title": string;
                "update-badman": string;
                "update-visual": string;
                "warnings": {
                    "closed": string;
                    "closing": string;
                    "home-accept": string;
                    "location-change": string;
                    "missing-availability": string;
                    "selected-different-location": string;
                };
            };
            "club-assembly": {
                "description": string;
                "note": string;
                "warnings": {
                    "base": string;
                    "base-subevent": string;
                    "better-meta": string;
                    "min-level": string;
                    "other-gender": string;
                    "title": string;
                };
            };
            "draw": {
                "encounters": string;
                "title": string;
            };
            "encounters": {
                "change-date": string;
                "change-location": string;
                "change-location-note": string;
                "gameleader": string;
                "home-games": string;
                "no-more": string;
                "open-requests": string;
                "shuttle": string;
                "title": string;
            };
            "home": string;
            "last-updated": string;
            "liga": string;
            "load-more": string;
            "map": {
                "title": string;
            };
            "menu": {
                "actions": string;
                "add-event": string;
                "averages": string;
                "copy": string;
                "dates": string;
                "download-base-players": string;
                "download-cp": string;
                "make-official": string;
                "new-date": string;
                "open_close_change-encounters": string;
                "open_close_enrollments": string;
                "reports": string;
                "sync": string;
                "unmake-official": string;
            };
            "national": string;
            "no-more-games": string;
            "note": string;
            "open-close": {
                "close-accept-requests": string;
                "close-enrollment": string;
                "close-new-requets": string;
                "hint": string;
                "open-enrollment": string;
                "open-requests": string;
            };
            "overview": {
                "official": string;
                "only-official": string;
            };
            "prov": string;
            "subevent": {
                "max": string;
                "max-base": string;
                "min-base": string;
                "name": {
                    "none": string;
                    "plural": string;
                    "singular": string;
                };
                "title": string;
            };
            "team-assembly": {
                "avg-level": string;
                "captain": string;
                "change-team": string;
                "disclaimer": string;
                "double1": string;
                "double2": string;
                "double3": string;
                "double4": string;
                "download": string;
                "errors": {
                    "already": string;
                    "club-base-other-team": string;
                    "comp-status": string;
                    "comp-status-html": string;
                    "none": string;
                    "not-enough-players": string;
                    "player-above-lower": string;
                    "player-gender": string;
                    "player-genders": string;
                    "player-max-double-games": string;
                    "player-max-mix-games": string;
                    "player-max-mixed-games": string;
                    "player-max-single-games": string;
                    "player-min-level": string;
                    "player-order-doubles": string;
                    "player-order-highest": string;
                    "player-order-single": string;
                    "players-above-lower": string;
                    "team-index": string;
                    "team-to-strong": string;
                    "title": string;
                    "to-much": string;
                };
                "info": string;
                "level-exemption": string;
                "mix1": string;
                "mix2": string;
                "mix3": string;
                "mix4": string;
                "players": {
                    "backup": string;
                    "base": string;
                    "team": string;
                    "title": string;
                };
                "single1": string;
                "single2": string;
                "single3": string;
                "single4": string;
                "substitude": string;
                "team-index": string;
                "team-index-ignored": string;
                "title": string;
                "warnings": {
                    "subtitute-team-index": string;
                };
            };
            "team-enrollment": {
                "close": string;
                "closed": string;
                "comments": {
                    "liga": string;
                    "nat": string;
                    "prov": string;
                    "title": string;
                };
                "enrollments": string;
                "errors": {
                    "already": string;
                    "base-other-team": string;
                    "comp-status-base": string;
                    "comp-status-team": string;
                    "faller": string;
                    "first-team-index": string;
                    "no-subevent": string;
                    "none": string;
                    "player-club": string;
                    "player-club-none": string;
                    "player-gender": string;
                    "player-min-level": string;
                    "player-subevent": string;
                    "riser": string;
                    "team-index": string;
                    "team-order": string;
                    "team-order-same-subevent": string;
                    "team-to-strong": string;
                    "team-to-week": string;
                    "title": string;
                    "too-few-base-players": string;
                    "too-many-base-players": string;
                };
                "example-error": string;
                "example-warning": string;
                "exceptions": string;
                "info": string;
                "loan-locked": string;
                "locations": {
                    "availible-courts": string;
                    "courts-hint": string;
                    "title": string;
                };
                "open": string;
                "play-days": string;
                "players": {
                    "backup": string;
                    "base": string;
                    "loan": string;
                    "regular": string;
                    "team": string;
                    "title": string;
                    "transfer": string;
                };
                "save-and-continue-tooltip": string;
                "saved": string;
                "saved-failed": string;
                "select-club": string;
                "select-events": string;
                "select-location": string;
                "select-teams": string;
                "select-teams-description": string;
                "teams": {
                    "captain": string;
                    "change-team": string;
                    "new-teams": string;
                    "substitude": string;
                    "team-index": string;
                    "team-index-ignored": string;
                };
                "title": string;
                "transfer": {
                    "enrolled-as": string;
                    "transfer-teams": string;
                    "transfer-teams-description": string;
                };
                "transfer-locked": string;
                "transfers-players": string;
                "validations": string;
                "warnings": {
                    "subtitute-team-index": string;
                    "title": string;
                };
            };
            "title": string;
            "type": string;
            "vs": string;
            "vs-short": string;
        };
        "countries": {
            "be": {
                "antwerpen": string;
                "brabant-wallon": string;
                "brussels-hoofdstedelijk-gewest": string;
                "hainaut": string;
                "liege": string;
                "limburg": string;
                "luxembourg": string;
                "name": string;
                "namur": string;
                "oost-vlaanderen": string;
                "vlaams-brabant": string;
                "west-vlaanderen": string;
            };
        };
        "days": {
            "friday": string;
            "monday": string;
            "saturday": string;
            "sunday": string;
            "thursday": string;
            "tuesday": string;
            "wednesday": string;
        };
        "event": {
            "checkEncounterForFilledIn": string;
            "last-sync": string;
            "standing": {
                "games": string;
                "lost": string;
                "name": string;
                "played": string;
                "points": string;
                "sets": string;
                "spoiler": string;
                "tied": string;
                "title": string;
                "totalPoints": string;
                "won": string;
            };
            "type": string;
            "types": {
                "competition": string;
                "tournament": string;
            };
            "usedRankingNote": string;
        };
        "evolution": {
            "warning": string;
        };
        "faq": {
            "info": {
                "description": string;
                "title": string;
            };
            "legend": string;
            "overview": {
                "description": string;
                "evolution-1": string;
                "evolution-2": string;
                "game-result": string;
                "levels": string;
                "title": string;
            };
            "points": {
                "table": {
                    "level": string;
                    "points-needed-down": string;
                    "points-needed-up": string;
                    "points-won": string;
                };
                "title": string;
            };
            "ranking": {
                "description": string;
                "title": string;
            };
            "title": string;
            "updates": {
                "description": string;
                "title": string;
            };
        };
        "game": {
            "bye": string;
            "order": {
                "double": string;
                "female": string;
                "male": string;
                "mix": string;
                "mixed": string;
                "single": string;
            };
            "points": string;
            "recent": {
                "title": string;
            };
            "title": string;
            "types": {
                "double": string;
                "female": string;
                "long": {
                    "D": string;
                    "F": string;
                    "M": string;
                    "MX": string;
                    "S": string;
                };
                "male": string;
                "mix": string;
                "short": {
                    "double": string;
                    "female": string;
                    "male": string;
                    "mix": string;
                    "single": string;
                };
                "single": string;
                "title": string;
            };
            "unkown": string;
            "upcoming": {
                "title": string;
            };
        };
        "gender": {
            "female": string;
            "females": string;
            "long": {
                "F": string;
                "M": string;
                "MX": string;
            };
            "longs": {
                "F": string;
                "M": string;
            };
            "male": string;
            "males": string;
            "mix": string;
            "national": string;
            "select": string;
            "short": {
                "female": string;
                "male": string;
                "mix": string;
            };
            "title": string;
        };
        "input": {
            "abbreviation": string;
            "availible-courts": string;
            "city": string;
            "competitionplayer": string;
            "courts": string;
            "date": string;
            "date-range": string;
            "day": string;
            "email": string;
            "end-hour": string;
            "error": {
                "email": string;
                "required": string;
            };
            "fax": string;
            "firstname": string;
            "fullName": string;
            "gender": string;
            "hour": string;
            "lastname": string;
            "latitude": string;
            "longitude": string;
            "memberId": string;
            "name": string;
            "phone": string;
            "postalcode": string;
            "required": string;
            "select": string;
            "shuttle": string;
            "start-hour": string;
            "state": string;
            "street": string;
            "streetnumber": string;
            "sub": string;
            "this-required": string;
            "type": string;
            "year": string;
        };
        "jobs": {
            "title": string;
        };
        "landing": {
            "description": string;
            "title": string;
        };
        "lists": {
            "name": string;
        };
        "loading": string;
        "locations": {
            "add-day": string;
            "add-exception": string;
            "days": string;
            "exceptions": string;
            "hint": string;
            "title": string;
        };
        "management": {
            "calculate": string;
            "cleanup": string;
            "download": string;
            "end": string;
            "force": string;
            "games-to-use": string;
            "import": string;
            "new-system": string;
            "number-short": string;
            "procent-losing-short": string;
            "procent-winning-short": string;
            "ranking": string;
            "reset": string;
            "select": string;
            "start": string;
            "sync": string;
        };
        "months": {
            "april": string;
            "august": string;
            "december": string;
            "february": string;
            "january": string;
            "june": string;
            "march": string;
            "may": string;
            "november": string;
            "october": string;
            "september": string;
        };
        "notifications": {
            "noNotifications": string;
            "types": {
                "encounterNotAcceptedNotification": string;
                "encounterNotEnteredNotification": string;
            };
        };
        "permission": {
            "no-perm": string;
        };
        "pickers": {
            "end-time": string;
            "none": string;
            "select-club": string;
            "select-country": string;
            "select-encounter": string;
            "select-end-time": string;
            "select-event-competition": string;
            "select-player": string;
            "select-season": string;
            "select-start-time": string;
            "select-state": string;
            "select-subevent-competition": string;
            "select-team": string;
            "select-team-groups": {
                "F": string;
                "M": string;
                "MX": string;
                "NATIONAL": string;
            };
            "select-year": string;
            "start-time": string;
        };
        "player": {
            "backup": string;
            "base": string;
            "claimed": string;
            "menu": {
                "add": string;
                "claim": string;
                "delete": string;
                "edit": string;
            };
            "no-memberid": string;
            "no-players": string;
            "regular": string;
            "search": {
                "backup-player": string;
                "create": string;
                "in-list": string;
                "label": string;
                "not-found": string;
            };
            "title": string;
        };
        "points": {
            "title": string;
        };
        "ranking": {
            "all-ranking": string;
            "breakdown": {
                "add-game": {
                    "p1t1": string;
                    "p1t2": string;
                    "p2t1": string;
                    "p2t2": string;
                    "title": string;
                    "won": string;
                };
                "can-downgrade": string;
                "can-not-downgrade": string;
                "can-not-upgrade": string;
                "can-upgrade": string;
                "corrected": string;
                "date": string;
                "disclaimer": string;
                "downgrade": string;
                "drops-next-period": string;
                "evolution": string;
                "hint": string;
                "ignored": string;
                "includeOutOfScope": string;
                "lostGames": {
                    "none": string;
                    "one": string;
                    "other": string;
                };
                "no-tean": string;
                "noGames": string;
                "notUsed": string;
                "opponent": string;
                "outOfScope": {
                    "none": string;
                    "one": string;
                    "other": string;
                };
                "period": {
                    "last-point-update": string;
                    "last-ranking-update": string;
                    "next-point-update": string;
                    "next-ranking-update": string;
                    "title": string;
                };
                "points": string;
                "pointsPerGame": string;
                "removed-games": string;
                "team": string;
                "title": string;
                "untill": string;
                "update": {
                    "last": string;
                    "point": string;
                    "ranking": string;
                };
                "upgrade": string;
                "usedForDowngrade": string;
                "usedForUpgrade": string;
            };
            "clone-points": string;
            "double": string;
            "double-points": string;
            "double-rank": string;
            "inactive": {
                "double": string;
                "mix": string;
                "single": string;
            };
            "last-ranking": string;
            "last-update": string;
            "list": string;
            "may-ranking": string;
            "menu": {
                "add-ranking": string;
                "add-system": string;
            };
            "mix": string;
            "mix-points": string;
            "mix-rank": string;
            "next-ranking": string;
            "single": string;
            "single-points": string;
            "single-rank": string;
            "table": {
                "title": string;
            };
            "title": string;
            "trending_down": string;
            "trending_up": string;
            "update-happend": string;
            "updates": string;
            "upload": {
                "comp-status": string;
                "create-new-players": string;
                "description": string;
                "hint": string;
                "preview": string;
                "ranking-date": string;
                "remove-current-ranking": string;
                "title": string;
                "update-possible": string;
                "update-ranking": string;
            };
        };
        "search": {
            "placeholder": string;
            "type": {
                "club": string;
                "eventcompetition": string;
                "eventtournament": string;
                "player": string;
            };
        };
        "security": {
            "claims": {
                "edit": {
                    "title": string;
                };
            };
            "roles": {
                "locked": string;
            };
        };
        "settings": {
            "general": {
                "title": string;
            };
            "languages": {
                "en": string;
                "fr_BE": string;
                "nl_BE": string;
                "title": string;
            };
            "notifications": {
                "disclaimer": string;
                "encounter": {
                    "notAcceptedNotification": string;
                    "notEnteredNotification": string;
                    "title": string;
                };
                "encounterChange": {
                    "confirmationNotification": string;
                    "finishedNotification": string;
                    "newNotification": string;
                    "title": string;
                };
                "enrollment": {
                    "clubenrollment": string;
                    "title": string;
                };
                "messages": {
                    "clubEnrollmentNotification": string;
                    "encounterChangeConfirmationNotification": string;
                    "encounterChangeFinishedNotification": string;
                    "encounterChangeNewNotification": string;
                    "encounterNotAcceptedNotification": string;
                    "encounterNotEnteredNotification": string;
                    "syncFailedNotification": string;
                    "syncSuccessNotification": string;
                };
                "sync": {
                    "failed": string;
                    "success": string;
                    "title": string;
                };
                "title": string;
                "types": {
                    "email": string;
                    "none": string;
                    "push": string;
                    "sms": string;
                };
            };
            "title": string;
        };
        "shell": {
            "sidebar": {
                "competition": {
                    "assembly": string;
                    "change-encounter": string;
                    "enrollment": string;
                    "overview": string;
                    "title": string;
                };
                "general": {
                    "changelog": string;
                    "faq": string;
                    "title": string;
                };
                "jobs": {
                    "title": string;
                };
                "persnal": {
                    "club": string;
                    "games": string;
                };
                "ranking": {
                    "title": string;
                };
                "tournament": {
                    "title": string;
                };
            };
        };
        "team": {
            "change-event": {
                "change": string;
                "pick": string;
                "select-event-hint": string;
            };
            "change-number": {
                "description": string;
                "number": string;
                "title": string;
                "tooltip": string;
            };
            "check-players": string;
            "edit": string;
            "location": string;
            "no-perm": {
                "email-phone": string;
            };
            "prefferd": {
                "title": string;
            };
            "team-index": string;
            "teams": string;
            "title": {
                "base-fields": string;
                "captain": string;
                "players": string;
                "prefferd-encounter": string;
            };
            "types": {
                "female": string;
                "long": {
                    "F": string;
                    "M": string;
                    "MX": string;
                    "NATIONAL": string;
                };
                "male": string;
                "mix": string;
                "national": string;
                "short": {
                    "female": string;
                    "male": string;
                    "mix": string;
                    "national": string;
                };
                "title": string;
            };
            "usedForTeam": {
                "description": string;
                "example": string;
                "select": string;
                "title": string;
            };
        };
        "themes": {
            "dark": string;
            "light": string;
        };
        "tournament": {
            "away": string;
            "delete": {
                "description": string;
                "title": string;
            };
            "draw": {
                "games": string;
                "title": string;
            };
            "enrollment": {
                "close": string;
                "closed": string;
                "open": string;
                "title": string;
            };
            "home": string;
            "last-updated": string;
            "liga": string;
            "load-more": string;
            "menu": {
                "add-event": string;
            };
            "note": string;
            "overview": {
                "date": string;
                "menu": {
                    "add-event": string;
                    "delete": string;
                    "edit": string;
                    "set-open-close": string;
                    "sync": string;
                };
                "name": string;
                "nothing-found": string;
                "official": string;
                "only-official": string;
            };
            "prov": string;
            "subevent": {
                "max": string;
                "max-base": string;
                "min-base": string;
            };
            "title": string;
            "type": string;
            "vs": string;
            "vs-short": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
