{{ if .Values.image.private }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}