import { Module } from "@nestjs/common";
import path, { join } from "path";
import { TranslateController } from "./controllers";
import { I18nModule, QueryResolver } from "nestjs-i18n";
import fs from "fs";

const i18nGeneratedPath = join(__dirname, "../../../libs/utils/src/lib/i18n.generated.ts");

const i18nStub = `/* DO NOT EDIT, file generated by nestjs-i18n */
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {};
export type I18nPath = Path<I18nTranslations>;`;
@Module({
  controllers: [TranslateController],
  imports: [
    I18nModule.forRootAsync({
      resolvers: [{ use: QueryResolver, options: ["lang"] }],

      useFactory: () => {
        // check if generated director/file exists
        const dir = path.dirname(i18nGeneratedPath);
        const file = i18nGeneratedPath;

        if (!fs.existsSync(file)) {
          fs.mkdirSync(dir, {
            recursive: true,
          });
          fs.writeFileSync(file, i18nStub, { encoding: "utf8" });
        }

        return {
          fallbackLanguage: "nl_BE",
          loaderOptions: {
            path: join(__dirname, `./assets/i18n/`),
            watch: true,
          },
          typesOutputPath: file,
        };
      },
    }),
  ],
  exports: [],
})
export class TranslateModule {}
