postgresql:
  replicaCount: 1
  existingSecret: server-postgresql-ha-postgresql

persistence:
  size: 18Gi

pgpool:
  existingSecret: server-postgresql-ha-pgpool
  extraEnvVars:
    - name: PGPOOL_AES_KEY
      value: phony
    - name: PGPOOL_AUTHENTICATION_METHOD
      value: scram-sha-256
  resources:
    requests:
      memory: "1Gi"

postgresqlImage:
  # tag: 14.5.0-debian-11-r25

pgpoolImage:
  # tag: 4.3.3-debian-11-r16