postgresql:
  replicaCount: 1
  existingSecret: server-postgresql-ha-postgresql

persistence:
  size: 18Gi

pgpool:
  existingSecret: server-postgresql-ha-pgpool
  extraEnvVars:
    - name: PGPOOL_AES_KEY
      value: phony
    - name: PGPOOL_AUTHENTICATION_METHOD
      value: scram-sha-256

postgresqlImage:
  tag: 14.2.0-debian-10-r4

pgpoolImage:
  tag: 4.3.1-debian-10-r0
