 
export enum EventImportType {
  COMPETITION_CP = 'COMPETITION_CP',
  COMPETITION_XML = 'COMPETITION_XML',
  TOURNAMENT = 'TOURNAMENT',
}

export enum EventType {
  COMPETITION = 'COMPETITION',
  TOURNAMENT = 'TOURNAMENT',
}
