replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
  repository: ghcr.io/badminton-apps/core/supervisor

service:
  internalPort: 4000
  externalPort: 80

auth0:
  issuer: https://badvlasim.eu.auth0.com
