apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: badvla-prod
  namespace: badvla
spec:
  dnsNames:
    - badman.app
  secretName: badvla-prod-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
