apiVersion: v2
description: Server
name: server
version: 0.3.5
appVersion: 0.3.5


dependencies:
  - name: postgresql
    version: 8.6.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
