apiVersion: v2
description: Server
name: server
version: 0.3.8
appVersion: 0.1.0


dependencies:
  - name: postgresql
    version: 10.3.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
