replicaCount: 1
image:
  useImagePullSecrets: true
  pullPolicy: Always
  repository: ghcr.io/badminton-apps/core/server

service:
  name: badman-server
  internalPort: 4000
  externalPort: 80

mysql:
  enabled: false
  mysqlUser: ranking
  mysqlDatabase: ranking
  configurationFiles:
    DB_custom.cnf: |-
      [server]
      max_allowed_packet = 100M

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlDatabase: ranking
  postgresqlExtendedConf: { 'sharedBuffers': '1000MB', 'maxConnections': 100 }
  resources:
    requests:
      memory: "1Gi"

APOLLO:
  APOLLO_KEY: service:Badman-PROD:DdwlGfdehSYN_RVG99YiQw
  APOLLO_GRAPH_ID: Badman-PROD
  APOLLO_GRAPH_VARIANT: current
  APOLLO_SCHEMA_REPORTING: "true"

database:
  DB_IP: server-postgresql.badvla
  DB_DATABASE: ranking
  DB_USER: postgres
  DB_DIALECT: postgres
  DB_PATH: ../_shared/dist/

services:
  simulate: simulate-simulate.badvla
  import: import-import.badvla
  job: jobs-jobs.badvla

auth0:
  issuer: https://badvlasim.eu.auth0.com

apm:
  active: true
  server: http://elastic-apm-apm-http.elastic:8200

esc:
  server: http://elastic-search-es-http.elastic:9200