apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: badvla-prod
  namespace: badvla
spec:
  dnsNames:
    - beta.latomme.org
    - latomme.org
  secretName: badvla-prod-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer