apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: badvla
spec:
  acme:
    # Staging API
    server: https://acme-v02.api.letsencrypt.org/directory
    email: glenn@latomme.org
    privateKeySecretRef:
      name: account-key-prod
    solvers:
    - selector: {}
      http01:
       ingress:
         class: nginx