replicaCount: 1
image:
  useImagePullSecrets: true
  pullPolicy: Always
  repository: ghcr.io/badminton-apps/core/simulate

service:
  internalPort: 4000
  externalPort: 80

services:
  supervisor: supervisor-supervisor.badvla

database:
  DB_IP: server-postgresql.badvla
  DB_DATABASE: ranking
  DB_USER: postgres
  DB_DIALECT: postgres

auth0:
  issuer: https://badvlasim.eu.auth0.com
