replicaCount: 1
image:
  useImagePullSecrets: true
  pullPolicy: Always
  repository: ghcr.io/badminton-apps/core/simulate

service:
  name: badman-simulate
  internalPort: 4003
  externalPort: 80

database:
  DB_IP: server-postgresql.badvla
  DB_DATABASE: ranking
  DB_USER: postgres
  DB_DIALECT: postgres

auth0:
  issuer: https://badvlasim.eu.auth0.com

apm:
  server: http://elastic-apm-apm-http.elastic:8200

esc:
  server: http://elastic-search-es-http.elastic:9200