name: Main Branch Workflow

on:
  push:
    branches:
      - main
    tags:
      - '!**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3
        npx nx affected --target=server

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 3

  Release:
    runs-on: ubuntu-latest
    needs: [main]

    steps:
      - name: Checkout [develop]
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: install dependencies for release
        run: |
          npm i -g standard-version conventional-changelog    

      - name: Create release
        run: |
          TAG_VERSION=$(git describe --match 'v*' --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "Found tag: $TAG_VERSION"
          LAST_TAG_HASH=$(git rev-list -n 1 $TAG_VERSION)
          echo "Found hash: $LAST_TAG_HASH"
          echo "base=$LAST_TAG_HASH"
          echo "version=$TAG_VERSION"
          git config --global user.email "info@badman.app"
          git config --global user.name "Badman Releaser"
          git config advice.ignoredHook false
          npm run create-release -- --beta --base=$TAG_VERSION --head=origin/develop
          git push origin main

      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          body: ${{ env.changelog  }}

      - name: Trigger deploy hooks on Render.com (if affected)
        run: |
          if [ -n "$(git diff --name-only HEAD^ HEAD -- packages/api)" ]; then
            curl -X POST -H "Content-Type: application/json" ${{ secrets.PROD_API_HOOK }}
          fi

      - name: Trigger deploy hook on Vercel.com (if affected)
        run: |
          if [ -n "$(git diff --name-only HEAD^ HEAD -- packages/badman)" ]; then
          curl -X POST -H "Content-Type: application/json" ${{ secrets.PROD_CLIENT_HOOK }}
          fi
