name: Main Branch Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.1

      - name: Install dependencies
        run: npm ci

      - name: Lint, test, build, and serve
        run: npx nx affected --target=lint,test,build,server

      - id: tag
        run: |
          TAG_VERSION=$(git describe --match 'v*' --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "Found tag: $TAG_VERSION"
          LAST_TAG_HASH=$(git rev-list -n 1 $TAG_VERSION)
          echo "Found hash: $LAST_TAG_HASH"
          echo "base=$LAST_TAG_HASH"
          echo "version=$TAG_VERSION"
          git config --global user.email "info@badman.app"
          git config --global user.name "Badman Releaser"
          git config advice.ignoredHook false
          npm run create-release -- --base=$TAG_VERSION --head=origin/develop
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          body: ${{ env.changelog  }}
      
      - name: Publish to main branch
        run: |
          git push origin main

      - name: Trigger deploy hooks on Render.com (if affected)
        run: |
          if [ -n "$(git diff --name-only HEAD^ HEAD -- packages/api)" ]; then
          curl -X POST -H "Content-Type: application/json" ${{ secrets.PROD_API_HOOK }}
          fi

      - name: Trigger deploy hook on Vercel.com (if affected)
        run: |
          if [ -n "$(git diff --name-only HEAD^ HEAD -- packages/badman)" ]; then
          curl -X POST -H "Content-Type: application/json" ${{ secrets.PROD_CLIENT_HOOK }}
          fi
