name: Release Workflow v2

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      # main branch name
      prod-release:
        description: 'Do prod release'
        required: true
        default: false
        type: boolean
      # main branch name
      e2e-tests:
        description: 'Do e2e tests'
        required: true
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: ${{ inputs.prod-release && 'Prod' || 'Beta' }} release ${{ inputs.e2e-tests && 'with E2E tests' || '' }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected -t lint test build e2e-ci
      - name: e2e reports
        run: |
          echo "Combine all the reports into a single report"
          # check if the "blob-reports" root directory exists and if it does, remove it and recreate it
          if [ -d "blob-reports" ]; then
            rm -rf blob-reports
          fi

          # create the "blob-reports" root directory
          mkdir blob-reports

          # copy all the reports into the "blob-reports" root directory
          cp apps/**/blob-report/*.zip ./blob-reports

          # create nx report
          npx playwright merge-reports --reporter=html,github ./blob-reports

          ## for copy pasting in shell
          # npx playwright show-report
      
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30