name: Deploy nx

on: workflow_dispatch

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: badman # Add your cluster name here.
  GKE_ZONE: europe-west1 # Add your cluster zone here.

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Install Dependencies'
        run: yarn install --frozen-lockfile

      - name: Standard Version
        run: |
          git config --global user.email "info@badman.app"
          git config --global user.name "Badman Releaser"
          yarn run standard-version

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - name: kubectl - Google Cloud GKE cluster.
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        env:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build project'
        run: npx nx affected --target=build

      - name: 'Build docker'
        run: npx nx affected --target=docker

      - name: 'Deploy'
        run: npx nx affected --target=deploy
