# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number || github.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NODE_ENV: '18.8.0'

jobs:
  base:
    defaults:
      run:
        working-directory: ./code
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.tag.outputs.base }}
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: tag
        run: |
          TAG_VERSION=$(git describe --match 'v*' --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "Found tag: $TAG_VERSION"
          LAST_TAG_HASH=$(git rev-list -n 1 $TAG_VERSION)
          echo "Found hash: $LAST_TAG_HASH"
          echo "base=$LAST_TAG_HASH" >> $GITHUB_OUTPUT
          echo "version=$TAG_VERSION" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v2
        with:
          version: latest
        name: Install pnpm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_ENV }}
          cache: 'pnpm'
          cache-dependency-path: './code/pnpm-lock.yaml'
      - name: pnpm-install
        run: pnpm install --no-frozen-lockfile --no-frozen-lockfile

  agents:
    name: Agent ${{ matrix.agent }}
    runs-on: ubuntu-latest
    needs: base
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./code
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

        name: Install pnpm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_ENV }}
          cache: 'pnpm'
          cache-dependency-path: './code/pnpm-lock.yaml'
      - name: pnpm-install
        run: pnpm install --no-frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  main:
    defaults:
      run:
        working-directory: ./code
    runs-on: ubuntu-latest
    needs: base
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: latest

        name: Install pnpm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_ENV }}
          cache: 'pnpm'
          cache-dependency-path: './code/pnpm-lock.yaml'
      - name: pnpm-install
        run: pnpm install --no-frozen-lockfile
      - run: npx nx-cloud start-ci-run
      - run: npx nx workspace-lint
      - run: npx nx format:write
      - run: npx nx affected --target=lint  --base=${{ needs.base.outputs.base }} --head=origin/main --parallel=3
      # - run: npx nx affected --target=test  --base=${{ needs.base.outputs.base }} --head=origin/main --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --base=${{ needs.base.outputs.base }} --head=origin/main --parallel=3
      - run: npx nx affected --target=send-coverage-reports --base=${{ needs.base.outputs.base }} --head=origin/main  --parallel=3
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: false
      - name: Standard Version
        run: |
          git config --global user.email "info@badman.app"
          git config --global user.name "Badman Releaser"
          git config advice.ignoredHook false
          pnpm create-release --base=${{ needs.base.outputs.base }} --head=origin/main
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: false
      - run: npx nx-cloud stop-all-agents
        if: always()
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          body: ${{ env.changelog  }}

  pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    if: ${{ github.event_name == 'pull_request' }}
    needs: base
    steps:
      - name: Checkout [pr]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: latest

        name: Install pnpm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_ENV }}
          cache: 'pnpm'
          cache-dependency-path: './code/pnpm-lock.yaml'
      - name: pnpm-install
        run: pnpm install --no-frozen-lockfile
      - run: npx nx-cloud start-ci-run
      - run: npx nx workspace-lint
      - run: npx nx format:write
      - run: npx nx affected --target=build --base=remotes/origin/main --parallel=3
      - run: npx nx affected --target=lint  --base=remotes/origin/main --parallel=3
      # - run: npx nx affected --target=test  --base=remotes/origin/main --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=send-coverage-reports --base=${{ needs.base.outputs.base }} --head=origin/main  --parallel=3
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: false
      - run: npx nx-cloud stop-all-agents
        if: always()

  docker-build:
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - main
      - base
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    env:
      NX_CLOUD_DISTRIBUTED_EXECUTION: false
      INPUT_PUSH: true
      GKE_CREDENTIALS: ${{ secrets.GKE_CREDENTIALS }}
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: badman
      GKE_ZONE: europe-west1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout latest release tag
        run: |
          LATEST_TAG=$(git describe --match 'v*' --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "LATEST_TAG=${LATEST_TAG:1}" >> $GITHUB_ENV
          echo "LATEST_TAG_V=$LATEST_TAG" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: ${{env.LATEST_TAG_V}}
      - id: 'auth'
        uses: 'google-github-actions/auth@v0.8.3'
        with:
          credentials_json: '${{ env.GKE_CREDENTIALS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0.8.2'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v2
        with:
          version: latest

        name: Install pnpm
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_ENV }}
          cache: 'pnpm'
          cache-dependency-path: './code/pnpm-lock.yaml'
      - name: pnpm-install
        run: pnpm install --no-frozen-lockfile

      - run: npx nx affected --target=build --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx affected --target=docker --base=${{ needs.base.outputs.base }} --head=origin/main
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_TAGS: ${{env.LATEST_TAG}}
      - run: npx nx affected --target=deploy --base=${{ needs.base.outputs.base }} --head=origin/main
