name: Deploy nx

on: workflow_dispatch

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Standart Version
        run: |
          git config --global user.email "info@badman.app"
          git config --global user.name "Badman Releaser"
          yarn run standard-version
          

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: europe-west1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Build project'
        run: npx nx affected --target=build

      - name: 'Build docker'
        run: npx nx affected --target=docker

      - name: 'Deploy'
        run: npx nx affected --target=deploy
