# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number || github.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  GKE_CREDENTIALS: ${{ secrets.GKE_CREDENTIALS }} # Add your cluster zone here.
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: badman # Add your cluster name here.
  GKE_ZONE: europe-west1 # Add your cluster zone here

jobs:
  base:
    defaults:
      run:
        working-directory: ./code
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.nx_hash.outputs.base }}
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: nx_hash
        run: |
          TAG_VERSION=$(git describe --match 'v*' --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "Found tag: $TAG_VERSION"
          LAST_TAG_HASH=$(git rev-list -n 1 $TAG_VERSION)
          echo "Found hash: $LAST_TAG_HASH"
          echo "::set-output name=base::$LAST_TAG_HASH"

  agents:
    name: Agent ${{ matrix.agent }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./code
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: ./code
      - run: yarn install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  main:
    defaults:
      run:
        working-directory: ./code
    runs-on: ubuntu-latest
    needs: base
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: ./code
      - run: yarn install --frozen-lockfile
      - name: Standard Version
        run: |
          git config --global user.email "info@badman.app"
          git config --global user.name "Badman Releaser"
          yarn run standard-version -- --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx affected --target=lint  --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx affected --target=test  --code-coverage --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx-cloud stop-all-agents

  pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    if: ${{ github.event_name == 'pull_request' }}
    needs: base
    steps:
      - name: Checkout [pr]
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: ./code
      - run: yarn install --frozen-lockfile
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target=build --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx affected --target=lint  --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx affected --target=test  --code-coverage --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx-cloud stop-all-agents

  docker-build:
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - main
      - base
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code
    env:
      NX_CLOUD_DISTRIBUTED_EXECUTION: false
      INPUT_PUSH: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: ./code
      - run: yarn install --frozen-lockfile
      - run: npx nx affected --target=build --base=${{ needs.base.outputs.base }} --head=origin/main
      - run: npx nx affected --target=docker --base=${{ needs.base.outputs.base }} --head=origin/main
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx nx affected --target=deploy --base=${{ needs.base.outputs.base }} --head=origin/main
