name: CI
on: [pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["backend", "frontend"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
      - run: npx lerna bootstrap
        working-directory: code/${{ matrix.folder }}
      - run: npx lerna run lint
        working-directory: code/${{ matrix.folder }}
      - run: npx lerna run build
        working-directory: code/${{ matrix.folder }}
