name: CI
on: 
  - pull_request_target
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      # We need to checkout the repository to access the configured file (.github/label-pr.yml)
      - uses: actions/checkout@v2
      - name: Labeler
        uses: actions/labeler@main
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Here we can override the path for the action configuration. If none is provided, default one is `.github/label-pr.yml`
          configuration-path: ${{ secrets.GITHUB_WORKSPACE }}/.github/label-pr.yml
  build:
    name: Bootstrap, Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["backend", "frontend"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
      - run: npx lerna bootstrap
        working-directory: code/${{ matrix.folder }}
      - run: npx lerna run lint
        working-directory: code/${{ matrix.folder }}
      - run: npx lerna run test
        working-directory: code/${{ matrix.folder }}
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: packages/**/lcov.info
          name: codecov-${{ matrix.folder }}
          verbose: true
          directory: code/${{ matrix.folder }}
      - run: npx lerna run build
        working-directory: code/${{ matrix.folder }}
