name: CI
on:
  - pull_request_target
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      # We need to checkout the repository to access the configured file (.github/label-pr.yml)
      - uses: actions/checkout@v2
      - name: Labeler
        uses: actions/labeler@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/label-pr.yml
  build:
    name: Bootstrap, Build & Test.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ['backend', 'frontend']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            ./code/${{ matrix.folder }}/node_modules
            ./code/${{ matrix.folder }}/*/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./code/${{ matrix.folder }}/yarn.lock') }}
      - run: npx lerna bootstrap
        working-directory: code/${{ matrix.folder }}
      - run: npm run lint
        working-directory: code/${{ matrix.folder }}
      - run: npm run test
        working-directory: code/${{ matrix.folder }}
      # - run: npm run e2e --if-present
      #   working-directory: code/${{ matrix.folder }}
      - uses: codecov/codecov-action@v1
        with:
          name: codecov-${{ matrix.folder }}
          directory: code/${{ matrix.folder }}
          override_pr: ${{ github.event.number }}
      - run: npm run build
        working-directory: code/${{ matrix.folder }}
