name: publish-docker
on: workflow_dispatch
jobs:
  docker-backend:
    strategy:
      matrix:
        pacakge: ['server']
    runs-on: ubuntu-latest
    steps:
      - name: Determine Version
        uses: gittools/actions/gitversion/setup@v0.9.7
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: badvla/${{ matrix.pacakge }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
