name: publish-docker
on: workflow_dispatch
jobs:
  docker-backend:
    strategy:
      matrix:
        pacakge: ['server']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context:  code/backend
          file: code/backend/packages/${{ matrix.pacakge }}Dockerfile
          tags: ${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}
