# A github actions that increases the version of the project
# and merges to master

name: Publish
on:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: develop
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_TOKEN }}
  NODE_ENV: '19.3.0'

jobs:
  base:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.tag.outputs.base }}
    steps:
      - name: Checkout [develop]
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: npm install
        run: npm ci
      - id: tag
        run: |
          TAG_VERSION=$(git describe --match 'v*' --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "Found tag: $TAG_VERSION"
          LAST_TAG_HASH=$(git rev-list -n 1 $TAG_VERSION)
          echo "Found hash: $LAST_TAG_HASH"
          echo "base=$LAST_TAG_HASH"
          echo "version=$TAG_VERSION"
          git config --global user.email "info@badman.app"
          git config --global user.name "Badman Releaser"
          git config advice.ignoredHook false
          npm run create-release --base=$TAG_VERSION --head=origin/develop
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          body: ${{ env.changelog  }}
      - name: Publish to main branch
        run: |
          git checkout main
          git merge develop
          git push origin main