import {
  Location,
  EventCompetition,
  Team,
  Club,
  EncounterCompetition,
  SubEventCompetition,
  DrawCompetition,
} from '@badman/backend-database';
import { Injectable, Logger } from '@nestjs/common';
import { writeFile } from 'fs/promises';
import moment from 'moment';
import xlsx from 'xlsx';

const cplocations = [
  {
    id: 68,
    name: 'Sporthal Ivo Van Damme',
    foreignid: '',
    locationid: '',
    address: 'Overstraat 21',
    postalcode: 3020,
    city: 'Veltem-Beisem',
    phone: null,
    clubid: 58,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 69,
    name: 'Sportcentrum Bart Swings',
    foreignid: '',
    locationid: '',
    address: 'Kouterstraat 1',
    postalcode: 3020,
    city: 'Herent',
    phone: null,
    clubid: 58,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 70,
    name: 'Den Willecom - Edegem',
    foreignid: '',
    locationid: '',
    address: 'Terelststraat 2',
    postalcode: 2650,
    city: 'Edegem',
    phone: '03/289.23.70',
    clubid: 59,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 71,
    name: 'Rozebroeken',
    foreignid: '',
    locationid: '',
    address: 'Victor Braeckmanlaan 180',
    postalcode: 9040,
    city: 'Sint-Amandsberg',
    phone: '0490446520',
    clubid: 60,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 72,
    name: 'STEDELIJKE SPORTHAL',
    foreignid: '',
    locationid: '',
    address: 'LAGAEPLEIN 3',
    postalcode: 8501,
    city: 'HEULE',
    phone: '056/35.05.13',
    clubid: 61,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 73,
    name: 'SPORTHAL Durmehal',
    foreignid: '',
    locationid: '',
    address: 'SPORTLAAN 2-3',
    postalcode: 9160,
    city: 'LOKEREN',
    phone: '09/340.50.88',
    clubid: 62,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 74,
    name: "'t Rosco",
    foreignid: '',
    locationid: '',
    address: 'Leuzesesteenweg 241',
    postalcode: 9600,
    city: 'RONSE',
    phone: '055/33.99.20',
    clubid: 63,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 75,
    name: 'DE HERNEKOUTER',
    foreignid: '',
    locationid: '',
    address: 'HERNEKOUTER 1',
    postalcode: 1540,
    city: 'HERNE',
    phone: '02/395.90.15',
    clubid: 64,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 76,
    name: "'Sporthal t Solveld",
    foreignid: '',
    locationid: '',
    address: 'Ralisweg 17',
    postalcode: 3390,
    city: 'Tielt Winge',
    phone: '016/63.95.69',
    clubid: 65,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 77,
    name: 'Sportcomplex Kessel-Lo',
    foreignid: '',
    locationid: '',
    address: 'Stadionlaan 4',
    postalcode: 3010,
    city: 'Kessel-Lo',
    phone: null,
    clubid: 66,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 78,
    name: 'GAVERHAL',
    foreignid: '',
    locationid: '',
    address: 'V. SOLARSTRAAT 30',
    postalcode: 8540,
    city: 'DEERLIJK',
    phone: '056/77.73.19',
    clubid: 67,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 79,
    name: 'Sportpunt 2',
    foreignid: '',
    locationid: '',
    address: 'Bekaertstraat 4',
    postalcode: 8550,
    city: 'Zwevegem',
    phone: null,
    clubid: 67,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 80,
    name: 'DE VALKAART',
    foreignid: '',
    locationid: '',
    address: 'A. RODENBACHSTRAAT 42',
    postalcode: 8020,
    city: 'OOSTKAMP',
    phone: '050/827289',
    clubid: 68,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 81,
    name: 'GC De Pit',
    foreignid: '',
    locationid: '',
    address: 'Platteput 14',
    postalcode: 9255,
    city: 'Buggenhout',
    phone: null,
    clubid: 69,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 82,
    name: 'Houtemveld',
    foreignid: '',
    locationid: '',
    address: 'Sporthalstraat T',
    postalcode: 3300,
    city: 'Houtemveld',
    phone: '016/81.74.14',
    clubid: 70,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 83,
    name: 'Sportoase Elshout - Brasschaat',
    foreignid: '',
    locationid: '',
    address: 'Zwembadweg 7 (GPS: Elshoutbaan 17)',
    postalcode: 2930,
    city: 'Brasschaat',
    phone: '03/289.28.90',
    clubid: 71,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 84,
    name: 'Sporthal Kiel - Antwerpen',
    foreignid: '',
    locationid: '',
    address: 'E. Vloorsstraat 2',
    postalcode: 2020,
    city: 'Antwerpen',
    phone: '03/237.89.59',
    clubid: 72,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 85,
    name: "Sporthal 't Kapelleke - Herenthout",
    foreignid: '',
    locationid: '',
    address: 'Bergensesteenweg 33',
    postalcode: 2270,
    city: 'Herenthout',
    phone: '014/51.62.06',
    clubid: 73,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 86,
    name: 'Polderbos',
    foreignid: '',
    locationid: '',
    address: 'Polderbos 20',
    postalcode: 9840,
    city: 'De Pinte',
    phone: null,
    clubid: 74,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 87,
    name: 'Hoge Heirweg',
    foreignid: '',
    locationid: '',
    address: 'Hoge Heirweg 64',
    postalcode: 9830,
    city: 'Sint-Martens-Latem',
    phone: null,
    clubid: 74,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 88,
    name: 'Sporthal K.A. Keerbergen',
    foreignid: '',
    locationid: '',
    address: 'Nachtegalendreef 7',
    postalcode: 3140,
    city: 'Keerbergen',
    phone: '',
    clubid: 75,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 89,
    name: 'STEDELIJKE SPORTHAL DE KREKEL',
    foreignid: '',
    locationid: '',
    address: 'H. HARTSTRAAT 15',
    postalcode: 8870,
    city: 'IZEGEM',
    phone: '051/30.33.22',
    clubid: 76,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 90,
    name: 'Wetteren Sporthal',
    foreignid: '',
    locationid: '',
    address: 'Warandelaan 14B',
    postalcode: 9230,
    city: 'Wetteren',
    phone: null,
    clubid: 77,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 91,
    name: 'OLVP Sint-Niklaas, Basisschool Plezantstraat',
    foreignid: '',
    locationid: '',
    address: 'Hofstraat 136',
    postalcode: 9100,
    city: 'Sint-Niklaas',
    phone: '0474520283',
    clubid: 78,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 92,
    name: 'Sportcentrum De Witte Molen',
    foreignid: '',
    locationid: '',
    address: 'Azalealaan 29',
    postalcode: 9100,
    city: 'Sint-Niklaas',
    phone: '03 778 37 60',
    clubid: 78,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 93,
    name: 'De Voordijcker',
    foreignid: '',
    locationid: '',
    address: 'Sportlaan 9',
    postalcode: 3980,
    city: '',
    phone: '0478069942',
    clubid: 79,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 94,
    name: 'Sporthal Helchteren',
    foreignid: '',
    locationid: '',
    address: 'Sportstraat 23',
    postalcode: 3530,
    city: '',
    phone: '011 52 13 01',
    clubid: 80,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 95,
    name: 'VZW Sport- en ontmoetingscentrum',
    foreignid: '',
    locationid: '',
    address: 'Dendermondestraat 25',
    postalcode: 1785,
    city: 'Merchtem',
    phone: '+3252371644',
    clubid: 81,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 96,
    name: 'DE PONTE',
    foreignid: '',
    locationid: '',
    address: 'sportlaan 3',
    postalcode: 8700,
    city: 'TIELT',
    phone: '051/428280',
    clubid: 82,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 97,
    name: 'KOUDE KEUKEN',
    foreignid: '',
    locationid: '',
    address: 'ZANDSTRAAT 284',
    postalcode: 8200,
    city: 'BRUGGE',
    phone: '050/31.91.02',
    clubid: 83,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 98,
    name: 'Sint-Lodewijkscollege',
    foreignid: '',
    locationid: '',
    address: 'Magdalenastraat 30',
    postalcode: 8200,
    city: 'Brugge',
    phone: '050 40 68 40',
    clubid: 83,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 99,
    name: 'Tempelhof',
    foreignid: '',
    locationid: '',
    address: 'Tempelhof 57',
    postalcode: 8000,
    city: 'Brugge',
    phone: null,
    clubid: 83,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 100,
    name: 'Sportcentrum Hoge Wal',
    foreignid: '',
    locationid: '',
    address: 'Guldensporenlaan 34',
    postalcode: 9940,
    city: 'Evergem',
    phone: null,
    clubid: 84,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 101,
    name: 'Eurohal Zelzate',
    foreignid: '',
    locationid: '',
    address: 'Oostkade 1',
    postalcode: 9060,
    city: 'Zelzate',
    phone: null,
    clubid: 84,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 102,
    name: 'Sporthal Klein Boom',
    foreignid: '',
    locationid: '',
    address: 'Mechelbaan 604',
    postalcode: 2580,
    city: 'Putte',
    phone: '015 25 24 07',
    clubid: 85,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 103,
    name: 'OLYMPIA',
    foreignid: '',
    locationid: '',
    address: 'P. VAN MIERLOLAAN 17',
    postalcode: 3550,
    city: 'HEUSDEN ZOLDER',
    phone: '',
    clubid: 86,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 104,
    name: 'BOURGOYEN',
    foreignid: '',
    locationid: '',
    address: 'DRIEPIKKELSTRAAT 30',
    postalcode: 9000,
    city: 'GENT',
    phone: '09/227.33.02',
    clubid: 87,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 105,
    name: 'Het Uitgedekt Schoor - Terhagen',
    foreignid: '',
    locationid: '',
    address: 'Europalaan 3',
    postalcode: 2840,
    city: 'Terhagen',
    phone: '03/888.07.83',
    clubid: 88,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 106,
    name: 'Sporthal Oostbroek',
    foreignid: '',
    locationid: '',
    address: 'Zeistraat 41',
    postalcode: 9850,
    city: 'Nevele',
    phone: null,
    clubid: 89,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 107,
    name: 'Sportcampus Sint-Gillis bij Dendermonde',
    foreignid: '',
    locationid: '',
    address: 'Van Langenhovestraat 203',
    postalcode: 9200,
    city: 'Sint-Gillis-bij-Dendermonde',
    phone: '052 21 06 12',
    clubid: 90,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 108,
    name: 'Sporthal Oudegem',
    foreignid: '',
    locationid: '',
    address: 'Ouburg 63',
    postalcode: 9200,
    city: 'Oudegem',
    phone: '052 22 32 51',
    clubid: 90,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 109,
    name: 'Stedelijke Sporthal Axion',
    foreignid: '',
    locationid: '',
    address: 'Zwaarvoerdersspoor 4',
    postalcode: 2440,
    city: 'Geel',
    phone: '0478448686',
    clubid: 91,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 110,
    name: 'SPORTHAL UC Leuven Limburg',
    foreignid: '',
    locationid: '',
    address: 'KERSPELSTRAAT 70',
    postalcode: 3001,
    city: 'HEVERLEE',
    phone: '016/39.90.98',
    clubid: 92,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 111,
    name: 'De Borg',
    foreignid: '',
    locationid: '',
    address: 'Rotemerlaan 34',
    postalcode: 3680,
    city: 'Neeroeteren',
    phone: '089863906',
    clubid: 93,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 112,
    name: 'DE SPIL',
    foreignid: '',
    locationid: '',
    address: 'BOUDEWIJNPLEIN 1',
    postalcode: 3650,
    city: 'DILSEN',
    phone: '089/79.08.30',
    clubid: 93,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 113,
    name: 'DE BLOKEN',
    foreignid: '',
    locationid: '',
    address: 'KORTESTRAAT 12',
    postalcode: 3830,
    city: 'WELLEN',
    phone: '012/74.20.33',
    clubid: 94,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 114,
    name: 'Sporthal Hazebeek Oostduinkerke',
    foreignid: '',
    locationid: '',
    address: 'Hazebeekstraat 11',
    postalcode: 8670,
    city: 'Oostduinkerke',
    phone: null,
    clubid: 95,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 115,
    name: 'Sporthal Den Oosthoek',
    foreignid: '',
    locationid: '',
    address: 'Sportlaan 2',
    postalcode: 8660,
    city: 'De Panne',
    phone: null,
    clubid: 95,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 116,
    name: 'De Treffer',
    foreignid: '',
    locationid: '',
    address: 'Meersstraat 5',
    postalcode: 8790,
    city: '',
    phone: '056600744',
    clubid: 96,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 117,
    name: 'Sporthal Arena - Walem',
    foreignid: '',
    locationid: '',
    address: 'Pastorijstraat 50',
    postalcode: 2800,
    city: 'Walem (Mechelen)',
    phone: '0496362549',
    clubid: 97,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 118,
    name: 'SPORTHAL HAASDONK',
    foreignid: '',
    locationid: '',
    address: 'ROPSTRAA T',
    postalcode: 9120,
    city: 'HAASDONK',
    phone: '',
    clubid: 98,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 119,
    name: 'Prov. Sportpark De Nekker',
    foreignid: '',
    locationid: '',
    address: 'Nekkerspoel Borcht 19',
    postalcode: 2800,
    city: 'Mechelen',
    phone: '015/55.70.05',
    clubid: 99,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 120,
    name: 'Sportzaal ‘Marie Thérèse De Gryse’',
    foreignid: '',
    locationid: '',
    address: 'Schapenstraat 45',
    postalcode: 8400,
    city: 'Oostende',
    phone: '',
    clubid: 100,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 121,
    name: "SPORTHAL' Den Bemvoort'",
    foreignid: '',
    locationid: '',
    address: 'JEUGDLAAN 8',
    postalcode: 3900,
    city: 'OVERPELT',
    phone: '011/64.04.99',
    clubid: 101,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 122,
    name: 'Sporthal Lembeke',
    foreignid: '',
    locationid: '',
    address: 'Heihoekse Kerkwegel 11',
    postalcode: 9971,
    city: 'Lembeke',
    phone: null,
    clubid: 102,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 123,
    name: 'Sporthal Mandelmeersen',
    foreignid: '',
    locationid: '',
    address: 'Ernest Brengierstraat ',
    postalcode: 8780,
    city: 'Oostrozebeke',
    phone: '056/67.11.40',
    clubid: 103,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 124,
    name: 'TEN GAERDE',
    foreignid: '',
    locationid: '',
    address: 'J. MERTENSSTRAAT 27A',
    postalcode: 1702,
    city: 'GROOT BIJGAARDEN',
    phone: '02/463.30.49',
    clubid: 104,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 125,
    name: 'Den Uyt - Mol',
    foreignid: '',
    locationid: '',
    address: 'Rode Kruislaan 20',
    postalcode: 2400,
    city: 'Mol',
    phone: '014/33.07.45',
    clubid: 105,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 126,
    name: 'TER LINDE',
    foreignid: '',
    locationid: '',
    address: 'TUINWIJK 2',
    postalcode: 8940,
    city: 'GELUWE',
    phone: '',
    clubid: 106,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 127,
    name: 'De Valk - Rijkevorsel',
    foreignid: '',
    locationid: '',
    address: 'Kruispad 6',
    postalcode: 2310,
    city: 'Rijkevorsel',
    phone: '03/314.75.75',
    clubid: 107,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 128,
    name: 'Gemeentelijke SPORTHAL',
    foreignid: '',
    locationid: '',
    address: 'BRUGGESTRAAT 104 A',
    postalcode: 8480,
    city: 'EERNEGEM',
    phone: '059/29.00.00',
    clubid: 108,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 129,
    name: "Sportcentrum 't Beerke - Beerse",
    foreignid: '',
    locationid: '',
    address: 'Rerum Novarumlaan 31',
    postalcode: 2340,
    city: 'Beerse',
    phone: '014/614724',
    clubid: 110,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 130,
    name: 'Sporthal Berkenbos',
    foreignid: '',
    locationid: '',
    address: 'Pastoor Paquaylaan 121',
    postalcode: 3550,
    city: 'Heusden-Zolder',
    phone: '011572618',
    clubid: 111,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 131,
    name: 'Sporthal Lubbeek',
    foreignid: '',
    locationid: '',
    address: 'Gellenberg 14',
    postalcode: 3210,
    city: 'Lubbeek',
    phone: '',
    clubid: 112,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 132,
    name: 'Sporthal Bourgoyen',
    foreignid: '',
    locationid: '',
    address: 'Driepikkelstraat 30',
    postalcode: 9030,
    city: 'Mariakerke',
    phone: null,
    clubid: 113,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 133,
    name: "sporthal 'college'",
    foreignid: '',
    locationid: '',
    address: 'Collegelaan 22',
    postalcode: 3990,
    city: 'PEER',
    phone: '',
    clubid: 114,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 135,
    name: 'Sportcentrum Benny Vansteelant',
    foreignid: '',
    locationid: '',
    address: 'Industrielaan 2',
    postalcode: 8820,
    city: 'Torhout',
    phone: '',
    clubid: 109,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
];

const cpClubs = [
  {
    id: 58,
    name: 'W&L BV',
    clubid: 20078,
    abbreviation: 'WLBV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 59,
    name: 'Olve',
    clubid: 10006,
    abbreviation: 'OBCV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 60,
    name: 'Pluimplukkers',
    clubid: 30027,
    abbreviation: 'PB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 61,
    name: 'Lebad Kortrijk',
    clubid: 40031,
    abbreviation: 'LK',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 62,
    name: 'Lokerse',
    clubid: 30042,
    abbreviation: 'LB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 63,
    name: 'Wit-Wit',
    clubid: 30055,
    abbreviation: 'WWB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 64,
    name: 'Herne',
    clubid: 20063,
    abbreviation: 'BCH',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 65,
    name: 'De Voskes',
    clubid: 20112,
    abbreviation: 'DVB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 66,
    name: 'Dijlevallei',
    clubid: 20006,
    abbreviation: 'DDV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 67,
    name: 'DZ99',
    clubid: 40023,
    abbreviation: 'D',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 68,
    name: 'De Valkaart',
    clubid: 40024,
    abbreviation: 'DV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 69,
    name: 'Buggenhout',
    clubid: 30026,
    abbreviation: 'BBV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 70,
    name: 'Tienen',
    clubid: 20004,
    abbreviation: 'TB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 71,
    name: 'Brasschaat',
    clubid: 10027,
    abbreviation: 'BBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 72,
    name: 'Royal Antwerp',
    clubid: 10002,
    abbreviation: 'RAB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 73,
    name: 'Huirtuits Dropke',
    clubid: 10078,
    abbreviation: 'tHD',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 74,
    name: 'Latem-De Pinte',
    clubid: 30007,
    abbreviation: 'BLDP',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 75,
    name: 'Tots Keerbergen',
    clubid: 20073,
    abbreviation: 'BTK',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 76,
    name: 'Izegemse',
    clubid: 40027,
    abbreviation: 'IZBA',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 77,
    name: 'Wetteren',
    clubid: 30022,
    abbreviation: 'BCW',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 78,
    name: 'De Mintons',
    clubid: 30001,
    abbreviation: 'BDM',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 79,
    name: 'Looise',
    clubid: 70015,
    abbreviation: 'LB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 80,
    name: 'Dropshot',
    clubid: 70010,
    abbreviation: 'DB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 81,
    name: 'Drop Merchtem',
    clubid: 20062,
    abbreviation: 'DMB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 82,
    name: 'Tielt',
    clubid: 40074,
    abbreviation: 'BT',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 83,
    name: 'Brugse',
    clubid: 40001,
    abbreviation: 'KBB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 84,
    name: 'Hoge Wal',
    clubid: 30080,
    abbreviation: 'HWB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 85,
    name: 'Klein Boom',
    clubid: 10090,
    abbreviation: 'KB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 86,
    name: 'Hebad',
    clubid: 70004,
    abbreviation: 'H',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 87,
    name: '4Ghent',
    clubid: 30004,
    abbreviation: '4B',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 88,
    name: 'De Klamp',
    clubid: 10029,
    abbreviation: 'DKB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 89,
    name: 'Landegem',
    clubid: 30050,
    abbreviation: 'LB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 90,
    name: 'Dendermondse',
    clubid: 30020,
    abbreviation: 'DB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 91,
    name: 'Geelse',
    clubid: 10050,
    abbreviation: 'GBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 92,
    name: 'Kill Leuven',
    clubid: 20077,
    abbreviation: 'KL',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 93,
    name: 'Dibad',
    clubid: 70030,
    abbreviation: 'DV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 94,
    name: 'Webacsa',
    clubid: 70036,
    abbreviation: 'OBTC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 95,
    name: 'Westhoek',
    clubid: 40044,
    abbreviation: 'WB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 96,
    name: 'Waregem',
    clubid: 40032,
    abbreviation: 'WB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 97,
    name: 'Opslag',
    clubid: 10095,
    abbreviation: 'BOV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 98,
    name: 'Beveren',
    clubid: 30005,
    abbreviation: 'BB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 99,
    name: 'De Nekker',
    clubid: 10051,
    abbreviation: 'DNB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 100,
    name: 'Oostendse',
    clubid: 40008,
    abbreviation: 'OBTC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 101,
    name: 'De Bokkerijder',
    clubid: 70001,
    abbreviation: 'DBB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 102,
    name: 'Smash For Fun',
    clubid: 30076,
    abbreviation: 'SFF',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 103,
    name: 'Oostrozebeke',
    clubid: 40041,
    abbreviation: 'OB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 104,
    name: 'Dilbeek',
    clubid: 20066,
    abbreviation: 'BD',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 105,
    name: 'Molse',
    clubid: 10016,
    abbreviation: 'MB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 106,
    name: 'Zuid-West',
    clubid: 40075,
    abbreviation: 'ZWB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 107,
    name: 'Rijkerack',
    clubid: 10065,
    abbreviation: 'RB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 108,
    name: 'Sportif',
    clubid: 40066,
    abbreviation: 'SV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 109,
    name: 'Torhout',
    clubid: 40011,
    abbreviation: 'TB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 110,
    name: 'Beerke',
    clubid: 10085,
    abbreviation: 'BtB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 111,
    name: 'Smash',
    clubid: 70013,
    abbreviation: 'SBL',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 112,
    name: 'Lubbinton',
    clubid: 20119,
    abbreviation: 'L',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 113,
    name: 'Gentse',
    clubid: 30009,
    abbreviation: 'GB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 114,
    name: 'BMC Peer',
    clubid: 70011,
    abbreviation: 'BBPV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 115,
    name: 'DENDERLEEUW BC',
    clubid: 30066,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 117,
    name: 'BLAUWPUT OMNISPORT VZW',
    clubid: 20105,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 118,
    name: 'Gitse Badmintonclub',
    clubid: 40004,
    abbreviation: 'Gitse BC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 119,
    name: 'BARLOKE',
    clubid: 40071,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 120,
    name: 'TURNHOUT BADMINTONCLUB',
    clubid: 10021,
    abbreviation: 'TBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 121,
    name: 'LEOBAD BC',
    clubid: 70005,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 122,
    name: 'KAMPENHOUT BC',
    clubid: 20064,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 123,
    name: 'Sporting Neerpelt Badminton Club',
    clubid: 70009,
    abbreviation: 'SNBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 124,
    name: 'Kraainem BC asbl',
    clubid: 23,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 7,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
];

@Injectable()
export class AddLocationsId {
  private readonly logger = new Logger(AddLocationsId.name);

  public async process() {
    // load excel file
    const eventId = '2625c52f-fae4-4a81-87ed-6819f44f1dcf';

    const teamMatches = xlsx.readFile(
      'apps/scripts/src/app/scripts/add-locations-to-cp/exportteammatches391192.xlsx'
    );
    const teamMatchesSheet = teamMatches.Sheets[teamMatches.SheetNames[0]];
    const teamMatchesJson = xlsx.utils.sheet_to_json<{
      matchid: number;
      plannedtime: string;
      plannedtime_original: string;
      drawid: number;
      eventid: number;
      team1name: string;
      team2name: string;
    }>(teamMatchesSheet);

    const data: (string | number | boolean)[][] = [
      [
        'matchid',
        'plannedtime',
        'round',
        'stage',
        'matchno',
        'reversehomeaway',
        'plannedtime_original',
        'locationId',
      ],
    ];

    const event = await EventCompetition.findByPk(eventId);
    const subEvents = await event?.getSubEventCompetitions();

    for (const teamMatch of teamMatchesJson) {
      const subEvent = subEvents?.find(
        (e) => e.visualCode === `${teamMatch.eventid}`
      );

      const draw = await subEvent?.getDrawCompetitions({
        where: {
          visualCode: `${teamMatch.drawid}`,
        },
      });

      if (!draw || draw.length === 0) {
        this.logger.warn(`Draw not found ${teamMatch.drawid}`);
        continue;
      }

      const encounter = await draw[0].getEncounterCompetitions({
        where: {
          visualCode: `${teamMatch.matchid}`,
        },
        include: [
          {
            model: Team,
            as: 'home',
            include: [
              {
                model: Club,
              },
            ],
          },
          { model: Team, as: 'away' },
        ],
      });

      if (!encounter || encounter.length === 0) {
        this.logger.warn(`Encounter not found ${teamMatch.matchid}`);

        continue;
      }

      const home = encounter[0].home;
      const away = encounter[0].away;

      if (!teamMatch.team1name.includes(home?.name ?? '')) {
        this.logger.warn(`Home team not found ${teamMatch.team1name}`);
        continue;
      }

      if (!teamMatch.team2name.includes(away?.name ?? '')) {
        this.logger.warn(`Home team not found ${teamMatch.team2name}`);
        continue;
      }

      const cpClub = cpClubs.find((c) => c.clubid == home?.club?.clubId);

      if (!cpClub) {
        this.logger.warn(`Club not found ${home?.club?.clubId}`);
        continue;
      }
      // parse teamMatch planned time as 'DD-MM-YYYY HH:MM:ss
      const plannedTime = moment(teamMatch.plannedtime, 'DD-MM-YYYY HH:mm:ss');

      if (!plannedTime.isSame(encounter[0].date, 'minute')) {
        this.logger.warn(`Planned is not the same ${teamMatch.plannedtime}`);
        continue;
      }

      const locationsForClub = cplocations.filter(
        (l) => l.clubid == cpClub?.id
      );

      let usedLocationId: number | undefined = undefined;

      if (!locationsForClub || locationsForClub.length === 0) {
        this.logger.warn(`No locations for club ${home?.club?.name}`);
        continue;
      }

      if (locationsForClub.length == 1) {
        usedLocationId = locationsForClub[0].id;
      } else {
        const location = await encounter[0].getLocation();

        // find if any have the same name
        const locationForClub = locationsForClub.find(
          (l) => l.name === location?.name
        );

        if (locationForClub) {
          usedLocationId = locationForClub.id;
        } else {
          this.logger.warn(
            `No location found for club ${home?.club?.name} and encounter ${encounter[0].id}`
          );
        }
      }

      if (!usedLocationId) {
        this.logger.warn(
          `No location found for club ${home?.club?.name} and encounter ${encounter[0].id}`
        );
        continue;
      }

      // const location = await encounter[0].getLocation();

      data.push([
        teamMatch.matchid,
        teamMatch.plannedtime,
        '', // round
        '', // stage
        '', // matchnos
        'false', // reversehomeaway
        teamMatch.plannedtime_original,
        usedLocationId, // locationId
      ]);
    }

    const newTeamMatchesSheet = xlsx.utils.aoa_to_sheet(data);
    // write export to csv
    const csv = xlsx.utils.sheet_to_csv(newTeamMatchesSheet);
    const csvBuffer = Buffer.from(csv, 'utf-8');
    await writeFile(
      'apps/scripts/src/app/scripts/add-locations-to-cp/export.csv',
      csvBuffer
    );
  }

  public async encountersWithLocations(eventId: string) {
    const teamMatches = xlsx.readFile(
      'apps/scripts/src/app/scripts/add-locations-to-cp/exportteammatches391192.xlsx'
    );
    const teamMatchesSheet = teamMatches.Sheets[teamMatches.SheetNames[0]];
    const teamMatchesJson = xlsx.utils.sheet_to_json<{
      matchid: number;
      plannedtime: string;
      plannedtime_original: string;
      drawid: number;
      eventid: number;
      team1name: string;
      team2name: string;
    }>(teamMatchesSheet);

    const data: (string | number | boolean)[][] = [
      [
        'matchid',
        'Home Club',
        'Home Team',
        'Away Team',
        'Datum',
        'Locatie ontmoeting',
        '',
        '',
        '',
        'Locatie Club 1',
        'Locatie Club 2',
        'Locatie Club 3',
      ],
    ];


    const event = await EventCompetition.findByPk(eventId);
    const subEvents = await event?.getSubEventCompetitions();

    for (const teamMatch of teamMatchesJson) {
      const subEvent = subEvents?.find(
        (e) => e.visualCode === `${teamMatch.eventid}`
      );

      const draw = await subEvent?.getDrawCompetitions({
        where: {
          visualCode: `${teamMatch.drawid}`,
        },
      });

      if (!draw || draw.length === 0) {
        this.logger.warn(`Draw not found ${teamMatch.drawid}`);
        continue;
      }

      const encounter = await draw[0].getEncounterCompetitions({
        where: {
          visualCode: `${teamMatch.matchid}`,
        },
        include: [
          {
            model: Team,
            as: 'home',
            include: [
              {
                model: Club,
                include: [
                  {
                    model: Location,
                  },
                ]
              },
            ],
          },
          { model: Team, as: 'away' },
        ],
      });

      if (!encounter || encounter.length === 0) {
        this.logger.warn(`Encounter not found ${teamMatch.matchid}`);

        continue;
      }

      const home = encounter[0].home;
      const away = encounter[0].away;

      if (!teamMatch.team1name.includes(home?.name ?? '')) {
        this.logger.warn(`Home team not found ${teamMatch.team1name}`);
        continue;
      }

      if (!teamMatch.team2name.includes(away?.name ?? '')) {
        this.logger.warn(`Home team not found ${teamMatch.team2name}`);
        continue;
      }

      const cpClub = cpClubs.find((c) => c.clubid == home?.club?.clubId);

      if (!cpClub) {
        this.logger.warn(`Club not found ${home?.club?.clubId}`);
        continue;
      }
      // parse teamMatch planned time as 'DD-MM-YYYY HH:MM:ss
      const plannedTime = moment(teamMatch.plannedtime, 'DD-MM-YYYY HH:mm:ss');

      if (!plannedTime.isSame(encounter[0].date, 'minute')) {
        this.logger.warn(`Planned is not the same ${teamMatch.plannedtime}`);
        continue;
      }

      const locationsForClub = cplocations.filter(
        (l) => l.clubid == cpClub?.id
      );

      let usedLocationId: number | undefined = undefined;

      if (!locationsForClub || locationsForClub.length === 0) {
        this.logger.warn(`No locations for club ${home?.club?.name}`);
        continue;
      }

      if (locationsForClub.length == 1) {
        usedLocationId = locationsForClub[0].id;
      } else {
        const location = await encounter[0].getLocation();

        // find if any have the same name
        const locationForClub = locationsForClub.find(
          (l) => l.name === location?.name
        );

        if (locationForClub) {
          usedLocationId = locationForClub.id;
        } else {
          this.logger.warn(
            `No location found for club ${home?.club?.name} and encounter ${encounter[0].id}`
          );
        }
      }

      if (!usedLocationId) {
        this.logger.warn(
          `No location found for club ${home?.club?.name} and encounter ${encounter[0].id}`
        );
        continue;
      }

     
      data.push([
        teamMatch.matchid,
        home?.club?.name || '',
        teamMatch.team1name || '',
        teamMatch.team2name || '',
        teamMatch.plannedtime || '',
        cplocations?.find((l) => l.id == usedLocationId)?.name || '',
        '',
        '',
        '',
        ...(home?.club?.locations?.map((l) => l.name || '') ??
          []),
      ]);
    }


    const ws = xlsx.utils.aoa_to_sheet(data);
    const wb = xlsx.utils.book_new();

    // Find the row with the most columns
    let indexWithMostColumns = 0;
    let maxColumns = 0;
    data.forEach((row, index) => {
      if (row.length > maxColumns) {
        maxColumns = row.length;
        indexWithMostColumns = index;
      }
    });

    // Autosize columns
    const columnSizes = data[indexWithMostColumns].map((_, columnIndex) =>
      data.reduce(
        (acc, row) => Math.max(acc, (`${row[columnIndex]}`.length ?? 0) + 2),
        0
      )
    );
    ws['!cols'] = columnSizes.map((width) => ({ width }));

    // Enable filtering
    ws['!autofilter'] = {
      ref: xlsx.utils.encode_range(
        xlsx.utils.decode_range(ws['!ref'] as string)
      ),
    };

    xlsx.utils.book_append_sheet(wb, ws, 'Encounter Data na sync');
    const fileName = `apps/scripts/src/app/scripts/add-locations-to-cp/export-encounters-and-locations-${event?.name}.xlsx`;
    xlsx.writeFile(wb, fileName);
  }
}
