export const cpClubsLimburg = [
  {
    id: 1,
    name: 'Looise',
    clubid: 70015,
    abbreviation: 'LB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 2,
    name: 'Opbad',
    clubid: 70014,
    abbreviation: 'OB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 3,
    name: 'Dibad',
    clubid: 70030,
    abbreviation: 'DV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 4,
    name: 'Dropshot',
    clubid: 70010,
    abbreviation: 'DB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 5,
    name: 'Poona Hoeselt',
    clubid: 70026,
    abbreviation: 'PHB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 6,
    name: 'BMC Peer',
    clubid: 70011,
    abbreviation: 'BBPV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 7,
    name: 'Hebad',
    clubid: 70004,
    abbreviation: 'H',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 8,
    name: 'Smash',
    clubid: 70013,
    abbreviation: 'SBL',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 9,
    name: 'De Bokkerijder',
    clubid: 70001,
    abbreviation: 'DBB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 10,
    name: "'t Plêmke Tongeren",
    clubid: 70043,
    abbreviation: 'BtPmT',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 11,
    name: 'BCZ Slagveld',
    clubid: 70053,
    abbreviation: 'BS',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 12,
    name: "BC Drive '83 Lanaken",
    clubid: 70028,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: '',
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 13,
    name: 'BILZERSE BC',
    clubid: 70020,
    abbreviation: 'BBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: '',
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 14,
    name: 'Sporting Neerpelt Badminton Club',
    clubid: 70009,
    abbreviation: 'SNBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: '',
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
  },
];

export const cpLocationsLimburg = [
  {
    id: 2,
    name: 'De Voordijcker',
    foreignid: '',
    locationid: '',
    address: 'Sportlaan 9',
    postalcode: 3980,
    city: '',
    phone: '0478069942',
    clubid: 1,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 3,
    name: 'Gemeentelijke Sporthal Opglabbeek',
    foreignid: '',
    locationid: '',
    address: 'Weg naar Gruitrode 2',
    postalcode: 3660,
    city: 'Oudsbergen',
    phone: '089/81.01.69',
    clubid: 2,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 4,
    name: 'De Borg',
    foreignid: '',
    locationid: '',
    address: 'Rotemerlaan 34',
    postalcode: 3680,
    city: 'Neeroeteren',
    phone: '089863906',
    clubid: 3,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 5,
    name: 'DE SPIL',
    foreignid: '',
    locationid: '',
    address: 'BOUDEWIJNPLEIN 1',
    postalcode: 3650,
    city: 'DILSEN',
    phone: '089/79.08.30',
    clubid: 3,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 6,
    name: 'Sporthal Helchteren',
    foreignid: '',
    locationid: '',
    address: 'Sportstraat 23',
    postalcode: 3530,
    city: '',
    phone: '011 52 13 01',
    clubid: 4,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 7,
    name: 'Sporthal Eigenbilzen',
    foreignid: '',
    locationid: '',
    address: 'Sporthalstraat 1',
    postalcode: 3740,
    city: 'Eigenbilzen',
    phone: null,
    clubid: 5,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 8,
    name: 'Sportcentrum Ter Kommen',
    foreignid: '',
    locationid: '',
    address: 'Europalaan 2',
    postalcode: 3730,
    city: 'Hoeselt',
    phone: '089/49 16 03',
    clubid: 5,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 9,
    name: "sporthal 'college'",
    foreignid: '',
    locationid: '',
    address: 'Collegelaan 22',
    postalcode: 3990,
    city: 'PEER',
    phone: '',
    clubid: 6,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 10,
    name: 'OLYMPIA',
    foreignid: '',
    locationid: '',
    address: 'P. VAN MIERLOLAAN 17',
    postalcode: 3550,
    city: 'HEUSDEN ZOLDER',
    phone: '',
    clubid: 7,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 11,
    name: 'Sporthal Berkenbos',
    foreignid: '',
    locationid: '',
    address: 'Pastoor Paquaylaan 121',
    postalcode: 3550,
    city: 'Heusden-Zolder',
    phone: '011572618',
    clubid: 8,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 12,
    name: "SPORTHAL' Den Bemvoort'",
    foreignid: '',
    locationid: '',
    address: 'JEUGDLAAN 8',
    postalcode: 3900,
    city: 'OVERPELT',
    phone: '011/64.04.99',
    clubid: 9,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 13,
    name: 'Cafetaria Sporthal Tio',
    foreignid: '',
    locationid: '',
    address: 'Koninksemsteenweg 79',
    postalcode: 3700,
    city: 'Tongeren',
    phone: null,
    clubid: 10,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 14,
    name: 'Sporthal Blookberg',
    foreignid: '',
    locationid: '',
    address: 'Bookbergstraat 7',
    postalcode: 3690,
    city: 'Zutendaal',
    phone: '089/61.37.53',
    clubid: 11,
  },
];

export const cpLocationsVlaamse = [
  {
    id: 68,
    name: 'Sporthal Ivo Van Damme',
    foreignid: '',
    locationid: '',
    address: 'Overstraat 21',
    postalcode: 3020,
    city: 'Veltem-Beisem',
    phone: null,
    clubid: 58,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 69,
    name: 'Sportcentrum Bart Swings',
    foreignid: '',
    locationid: '',
    address: 'Kouterstraat 1',
    postalcode: 3020,
    city: 'Herent',
    phone: null,
    clubid: 58,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 70,
    name: 'Den Willecom - Edegem',
    foreignid: '',
    locationid: '',
    address: 'Terelststraat 2',
    postalcode: 2650,
    city: 'Edegem',
    phone: '03/289.23.70',
    clubid: 59,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 71,
    name: 'Rozebroeken',
    foreignid: '',
    locationid: '',
    address: 'Victor Braeckmanlaan 180',
    postalcode: 9040,
    city: 'Sint-Amandsberg',
    phone: '0490446520',
    clubid: 60,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 72,
    name: 'STEDELIJKE SPORTHAL',
    foreignid: '',
    locationid: '',
    address: 'LAGAEPLEIN 3',
    postalcode: 8501,
    city: 'HEULE',
    phone: '056/35.05.13',
    clubid: 61,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 73,
    name: 'SPORTHAL Durmehal',
    foreignid: '',
    locationid: '',
    address: 'SPORTLAAN 2-3',
    postalcode: 9160,
    city: 'LOKEREN',
    phone: '09/340.50.88',
    clubid: 62,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 74,
    name: "'t Rosco",
    foreignid: '',
    locationid: '',
    address: 'Leuzesesteenweg 241',
    postalcode: 9600,
    city: 'RONSE',
    phone: '055/33.99.20',
    clubid: 63,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 75,
    name: 'DE HERNEKOUTER',
    foreignid: '',
    locationid: '',
    address: 'HERNEKOUTER 1',
    postalcode: 1540,
    city: 'HERNE',
    phone: '02/395.90.15',
    clubid: 64,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 76,
    name: "'Sporthal t Solveld",
    foreignid: '',
    locationid: '',
    address: 'Ralisweg 17',
    postalcode: 3390,
    city: 'Tielt Winge',
    phone: '016/63.95.69',
    clubid: 65,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 77,
    name: 'Sportcomplex Kessel-Lo',
    foreignid: '',
    locationid: '',
    address: 'Stadionlaan 4',
    postalcode: 3010,
    city: 'Kessel-Lo',
    phone: null,
    clubid: 66,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 78,
    name: 'GAVERHAL',
    foreignid: '',
    locationid: '',
    address: 'V. SOLARSTRAAT 30',
    postalcode: 8540,
    city: 'DEERLIJK',
    phone: '056/77.73.19',
    clubid: 67,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 79,
    name: 'Sportpunt 2',
    foreignid: '',
    locationid: '',
    address: 'Bekaertstraat 4',
    postalcode: 8550,
    city: 'Zwevegem',
    phone: null,
    clubid: 67,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 80,
    name: 'DE VALKAART',
    foreignid: '',
    locationid: '',
    address: 'A. RODENBACHSTRAAT 42',
    postalcode: 8020,
    city: 'OOSTKAMP',
    phone: '050/827289',
    clubid: 68,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 81,
    name: 'GC De Pit',
    foreignid: '',
    locationid: '',
    address: 'Platteput 14',
    postalcode: 9255,
    city: 'Buggenhout',
    phone: null,
    clubid: 69,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 82,
    name: 'Houtemveld',
    foreignid: '',
    locationid: '',
    address: 'Sporthalstraat T',
    postalcode: 3300,
    city: 'Houtemveld',
    phone: '016/81.74.14',
    clubid: 70,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 83,
    name: 'Sportoase Elshout - Brasschaat',
    foreignid: '',
    locationid: '',
    address: 'Zwembadweg 7 (GPS: Elshoutbaan 17)',
    postalcode: 2930,
    city: 'Brasschaat',
    phone: '03/289.28.90',
    clubid: 71,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 84,
    name: 'Sporthal Kiel - Antwerpen',
    foreignid: '',
    locationid: '',
    address: 'E. Vloorsstraat 2',
    postalcode: 2020,
    city: 'Antwerpen',
    phone: '03/237.89.59',
    clubid: 72,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 85,
    name: "Sporthal 't Kapelleke - Herenthout",
    foreignid: '',
    locationid: '',
    address: 'Bergensesteenweg 33',
    postalcode: 2270,
    city: 'Herenthout',
    phone: '014/51.62.06',
    clubid: 73,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 86,
    name: 'Polderbos',
    foreignid: '',
    locationid: '',
    address: 'Polderbos 20',
    postalcode: 9840,
    city: 'De Pinte',
    phone: null,
    clubid: 74,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 87,
    name: 'Hoge Heirweg',
    foreignid: '',
    locationid: '',
    address: 'Hoge Heirweg 64',
    postalcode: 9830,
    city: 'Sint-Martens-Latem',
    phone: null,
    clubid: 74,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 88,
    name: 'Sporthal K.A. Keerbergen',
    foreignid: '',
    locationid: '',
    address: 'Nachtegalendreef 7',
    postalcode: 3140,
    city: 'Keerbergen',
    phone: '',
    clubid: 75,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 89,
    name: 'STEDELIJKE SPORTHAL DE KREKEL',
    foreignid: '',
    locationid: '',
    address: 'H. HARTSTRAAT 15',
    postalcode: 8870,
    city: 'IZEGEM',
    phone: '051/30.33.22',
    clubid: 76,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 90,
    name: 'Wetteren Sporthal',
    foreignid: '',
    locationid: '',
    address: 'Warandelaan 14B',
    postalcode: 9230,
    city: 'Wetteren',
    phone: null,
    clubid: 77,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 91,
    name: 'OLVP Sint-Niklaas, Basisschool Plezantstraat',
    foreignid: '',
    locationid: '',
    address: 'Hofstraat 136',
    postalcode: 9100,
    city: 'Sint-Niklaas',
    phone: '0474520283',
    clubid: 78,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 92,
    name: 'Sportcentrum De Witte Molen',
    foreignid: '',
    locationid: '',
    address: 'Azalealaan 29',
    postalcode: 9100,
    city: 'Sint-Niklaas',
    phone: '03 778 37 60',
    clubid: 78,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 93,
    name: 'De Voordijcker',
    foreignid: '',
    locationid: '',
    address: 'Sportlaan 9',
    postalcode: 3980,
    city: '',
    phone: '0478069942',
    clubid: 79,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 94,
    name: 'Sporthal Helchteren',
    foreignid: '',
    locationid: '',
    address: 'Sportstraat 23',
    postalcode: 3530,
    city: '',
    phone: '011 52 13 01',
    clubid: 80,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 95,
    name: 'VZW Sport- en ontmoetingscentrum',
    foreignid: '',
    locationid: '',
    address: 'Dendermondestraat 25',
    postalcode: 1785,
    city: 'Merchtem',
    phone: '+3252371644',
    clubid: 81,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 96,
    name: 'DE PONTE',
    foreignid: '',
    locationid: '',
    address: 'sportlaan 3',
    postalcode: 8700,
    city: 'TIELT',
    phone: '051/428280',
    clubid: 82,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 97,
    name: 'KOUDE KEUKEN',
    foreignid: '',
    locationid: '',
    address: 'ZANDSTRAAT 284',
    postalcode: 8200,
    city: 'BRUGGE',
    phone: '050/31.91.02',
    clubid: 83,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 98,
    name: 'Sint-Lodewijkscollege',
    foreignid: '',
    locationid: '',
    address: 'Magdalenastraat 30',
    postalcode: 8200,
    city: 'Brugge',
    phone: '050 40 68 40',
    clubid: 83,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 99,
    name: 'Tempelhof',
    foreignid: '',
    locationid: '',
    address: 'Tempelhof 57',
    postalcode: 8000,
    city: 'Brugge',
    phone: null,
    clubid: 83,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 100,
    name: 'Sportcentrum Hoge Wal',
    foreignid: '',
    locationid: '',
    address: 'Guldensporenlaan 34',
    postalcode: 9940,
    city: 'Evergem',
    phone: null,
    clubid: 84,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 101,
    name: 'Eurohal Zelzate',
    foreignid: '',
    locationid: '',
    address: 'Oostkade 1',
    postalcode: 9060,
    city: 'Zelzate',
    phone: null,
    clubid: 84,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 102,
    name: 'Sporthal Klein Boom',
    foreignid: '',
    locationid: '',
    address: 'Mechelbaan 604',
    postalcode: 2580,
    city: 'Putte',
    phone: '015 25 24 07',
    clubid: 85,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 103,
    name: 'OLYMPIA',
    foreignid: '',
    locationid: '',
    address: 'P. VAN MIERLOLAAN 17',
    postalcode: 3550,
    city: 'HEUSDEN ZOLDER',
    phone: '',
    clubid: 86,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 104,
    name: 'BOURGOYEN',
    foreignid: '',
    locationid: '',
    address: 'DRIEPIKKELSTRAAT 30',
    postalcode: 9000,
    city: 'GENT',
    phone: '09/227.33.02',
    clubid: 87,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 105,
    name: 'Het Uitgedekt Schoor - Terhagen',
    foreignid: '',
    locationid: '',
    address: 'Europalaan 3',
    postalcode: 2840,
    city: 'Terhagen',
    phone: '03/888.07.83',
    clubid: 88,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 106,
    name: 'Sporthal Oostbroek',
    foreignid: '',
    locationid: '',
    address: 'Zeistraat 41',
    postalcode: 9850,
    city: 'Nevele',
    phone: null,
    clubid: 89,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 107,
    name: 'Sportcampus Sint-Gillis bij Dendermonde',
    foreignid: '',
    locationid: '',
    address: 'Van Langenhovestraat 203',
    postalcode: 9200,
    city: 'Sint-Gillis-bij-Dendermonde',
    phone: '052 21 06 12',
    clubid: 90,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 108,
    name: 'Sporthal Oudegem',
    foreignid: '',
    locationid: '',
    address: 'Ouburg 63',
    postalcode: 9200,
    city: 'Oudegem',
    phone: '052 22 32 51',
    clubid: 90,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 109,
    name: 'Stedelijke Sporthal Axion',
    foreignid: '',
    locationid: '',
    address: 'Zwaarvoerdersspoor 4',
    postalcode: 2440,
    city: 'Geel',
    phone: '0478448686',
    clubid: 91,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 110,
    name: 'SPORTHAL UC Leuven Limburg',
    foreignid: '',
    locationid: '',
    address: 'KERSPELSTRAAT 70',
    postalcode: 3001,
    city: 'HEVERLEE',
    phone: '016/39.90.98',
    clubid: 92,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 111,
    name: 'De Borg',
    foreignid: '',
    locationid: '',
    address: 'Rotemerlaan 34',
    postalcode: 3680,
    city: 'Neeroeteren',
    phone: '089863906',
    clubid: 93,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 112,
    name: 'DE SPIL',
    foreignid: '',
    locationid: '',
    address: 'BOUDEWIJNPLEIN 1',
    postalcode: 3650,
    city: 'DILSEN',
    phone: '089/79.08.30',
    clubid: 93,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 113,
    name: 'DE BLOKEN',
    foreignid: '',
    locationid: '',
    address: 'KORTESTRAAT 12',
    postalcode: 3830,
    city: 'WELLEN',
    phone: '012/74.20.33',
    clubid: 94,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 114,
    name: 'Sporthal Hazebeek Oostduinkerke',
    foreignid: '',
    locationid: '',
    address: 'Hazebeekstraat 11',
    postalcode: 8670,
    city: 'Oostduinkerke',
    phone: null,
    clubid: 95,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 115,
    name: 'Sporthal Den Oosthoek',
    foreignid: '',
    locationid: '',
    address: 'Sportlaan 2',
    postalcode: 8660,
    city: 'De Panne',
    phone: null,
    clubid: 95,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 116,
    name: 'De Treffer',
    foreignid: '',
    locationid: '',
    address: 'Meersstraat 5',
    postalcode: 8790,
    city: '',
    phone: '056600744',
    clubid: 96,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 117,
    name: 'Sporthal Arena - Walem',
    foreignid: '',
    locationid: '',
    address: 'Pastorijstraat 50',
    postalcode: 2800,
    city: 'Walem (Mechelen)',
    phone: '0496362549',
    clubid: 97,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 118,
    name: 'SPORTHAL HAASDONK',
    foreignid: '',
    locationid: '',
    address: 'ROPSTRAA T',
    postalcode: 9120,
    city: 'HAASDONK',
    phone: '',
    clubid: 98,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 119,
    name: 'Prov. Sportpark De Nekker',
    foreignid: '',
    locationid: '',
    address: 'Nekkerspoel Borcht 19',
    postalcode: 2800,
    city: 'Mechelen',
    phone: '015/55.70.05',
    clubid: 99,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 120,
    name: 'Sportzaal ‘Marie Thérèse De Gryse’',
    foreignid: '',
    locationid: '',
    address: 'Schapenstraat 45',
    postalcode: 8400,
    city: 'Oostende',
    phone: '',
    clubid: 100,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 121,
    name: "SPORTHAL' Den Bemvoort'",
    foreignid: '',
    locationid: '',
    address: 'JEUGDLAAN 8',
    postalcode: 3900,
    city: 'OVERPELT',
    phone: '011/64.04.99',
    clubid: 101,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 122,
    name: 'Sporthal Lembeke',
    foreignid: '',
    locationid: '',
    address: 'Heihoekse Kerkwegel 11',
    postalcode: 9971,
    city: 'Lembeke',
    phone: null,
    clubid: 102,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 123,
    name: 'Sporthal Mandelmeersen',
    foreignid: '',
    locationid: '',
    address: 'Ernest Brengierstraat ',
    postalcode: 8780,
    city: 'Oostrozebeke',
    phone: '056/67.11.40',
    clubid: 103,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 124,
    name: 'TEN GAERDE',
    foreignid: '',
    locationid: '',
    address: 'J. MERTENSSTRAAT 27A',
    postalcode: 1702,
    city: 'GROOT BIJGAARDEN',
    phone: '02/463.30.49',
    clubid: 104,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 125,
    name: 'Den Uyt - Mol',
    foreignid: '',
    locationid: '',
    address: 'Rode Kruislaan 20',
    postalcode: 2400,
    city: 'Mol',
    phone: '014/33.07.45',
    clubid: 105,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 126,
    name: 'TER LINDE',
    foreignid: '',
    locationid: '',
    address: 'TUINWIJK 2',
    postalcode: 8940,
    city: 'GELUWE',
    phone: '',
    clubid: 106,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 127,
    name: 'De Valk - Rijkevorsel',
    foreignid: '',
    locationid: '',
    address: 'Kruispad 6',
    postalcode: 2310,
    city: 'Rijkevorsel',
    phone: '03/314.75.75',
    clubid: 107,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 128,
    name: 'Gemeentelijke SPORTHAL',
    foreignid: '',
    locationid: '',
    address: 'BRUGGESTRAAT 104 A',
    postalcode: 8480,
    city: 'EERNEGEM',
    phone: '059/29.00.00',
    clubid: 108,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 129,
    name: "Sportcentrum 't Beerke - Beerse",
    foreignid: '',
    locationid: '',
    address: 'Rerum Novarumlaan 31',
    postalcode: 2340,
    city: 'Beerse',
    phone: '014/614724',
    clubid: 110,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 130,
    name: 'Sporthal Berkenbos',
    foreignid: '',
    locationid: '',
    address: 'Pastoor Paquaylaan 121',
    postalcode: 3550,
    city: 'Heusden-Zolder',
    phone: '011572618',
    clubid: 111,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 131,
    name: 'Sporthal Lubbeek',
    foreignid: '',
    locationid: '',
    address: 'Gellenberg 14',
    postalcode: 3210,
    city: 'Lubbeek',
    phone: '',
    clubid: 112,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 132,
    name: 'Sporthal Bourgoyen',
    foreignid: '',
    locationid: '',
    address: 'Driepikkelstraat 30',
    postalcode: 9030,
    city: 'Mariakerke',
    phone: null,
    clubid: 113,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 133,
    name: "sporthal 'college'",
    foreignid: '',
    locationid: '',
    address: 'Collegelaan 22',
    postalcode: 3990,
    city: 'PEER',
    phone: '',
    clubid: 114,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 135,
    name: 'Sportcentrum Benny Vansteelant',
    foreignid: '',
    locationid: '',
    address: 'Industrielaan 2',
    postalcode: 8820,
    city: 'Torhout',
    phone: '',
    clubid: 109,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
];

export const cpClubsVlaamse = [
  {
    id: 58,
    name: 'W&L BV',
    clubid: 20078,
    abbreviation: 'WLBV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 59,
    name: 'Olve',
    clubid: 10006,
    abbreviation: 'OBCV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 60,
    name: 'Pluimplukkers',
    clubid: 30027,
    abbreviation: 'PB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 61,
    name: 'Lebad Kortrijk',
    clubid: 40031,
    abbreviation: 'LK',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 62,
    name: 'Lokerse',
    clubid: 30042,
    abbreviation: 'LB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 63,
    name: 'Wit-Wit',
    clubid: 30055,
    abbreviation: 'WWB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 64,
    name: 'Herne',
    clubid: 20063,
    abbreviation: 'BCH',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 65,
    name: 'De Voskes',
    clubid: 20112,
    abbreviation: 'DVB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 66,
    name: 'Dijlevallei',
    clubid: 20006,
    abbreviation: 'DDV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 67,
    name: 'DZ99',
    clubid: 40023,
    abbreviation: 'D',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 68,
    name: 'De Valkaart',
    clubid: 40024,
    abbreviation: 'DV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 69,
    name: 'Buggenhout',
    clubid: 30026,
    abbreviation: 'BBV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 70,
    name: 'Tienen',
    clubid: 20004,
    abbreviation: 'TB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 71,
    name: 'Brasschaat',
    clubid: 10027,
    abbreviation: 'BBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 72,
    name: 'Royal Antwerp',
    clubid: 10002,
    abbreviation: 'RAB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 73,
    name: 'Huirtuits Dropke',
    clubid: 10078,
    abbreviation: 'tHD',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 74,
    name: 'Latem-De Pinte',
    clubid: 30007,
    abbreviation: 'BLDP',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 75,
    name: 'Tots Keerbergen',
    clubid: 20073,
    abbreviation: 'BTK',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 76,
    name: 'Izegemse',
    clubid: 40027,
    abbreviation: 'IZBA',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 77,
    name: 'Wetteren',
    clubid: 30022,
    abbreviation: 'BCW',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 78,
    name: 'De Mintons',
    clubid: 30001,
    abbreviation: 'BDM',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 79,
    name: 'Looise',
    clubid: 70015,
    abbreviation: 'LB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 80,
    name: 'Dropshot',
    clubid: 70010,
    abbreviation: 'DB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 81,
    name: 'Drop Merchtem',
    clubid: 20062,
    abbreviation: 'DMB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 82,
    name: 'Tielt',
    clubid: 40074,
    abbreviation: 'BT',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 83,
    name: 'Brugse',
    clubid: 40001,
    abbreviation: 'KBB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 84,
    name: 'Hoge Wal',
    clubid: 30080,
    abbreviation: 'HWB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 85,
    name: 'Klein Boom',
    clubid: 10090,
    abbreviation: 'KB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 86,
    name: 'Hebad',
    clubid: 70004,
    abbreviation: 'H',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 87,
    name: '4Ghent',
    clubid: 30004,
    abbreviation: '4B',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 88,
    name: 'De Klamp',
    clubid: 10029,
    abbreviation: 'DKB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 89,
    name: 'Landegem',
    clubid: 30050,
    abbreviation: 'LB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 90,
    name: 'Dendermondse',
    clubid: 30020,
    abbreviation: 'DB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 91,
    name: 'Geelse',
    clubid: 10050,
    abbreviation: 'GBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 92,
    name: 'Kill Leuven',
    clubid: 20077,
    abbreviation: 'KL',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 93,
    name: 'Dibad',
    clubid: 70030,
    abbreviation: 'DV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 94,
    name: 'Webacsa',
    clubid: 70036,
    abbreviation: 'OBTC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 95,
    name: 'Westhoek',
    clubid: 40044,
    abbreviation: 'WB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 96,
    name: 'Waregem',
    clubid: 40032,
    abbreviation: 'WB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 97,
    name: 'Opslag',
    clubid: 10095,
    abbreviation: 'BOV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 98,
    name: 'Beveren',
    clubid: 30005,
    abbreviation: 'BB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 99,
    name: 'De Nekker',
    clubid: 10051,
    abbreviation: 'DNB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 100,
    name: 'Oostendse',
    clubid: 40008,
    abbreviation: 'OBTC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 101,
    name: 'De Bokkerijder',
    clubid: 70001,
    abbreviation: 'DBB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 102,
    name: 'Smash For Fun',
    clubid: 30076,
    abbreviation: 'SFF',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 103,
    name: 'Oostrozebeke',
    clubid: 40041,
    abbreviation: 'OB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 104,
    name: 'Dilbeek',
    clubid: 20066,
    abbreviation: 'BD',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 105,
    name: 'Molse',
    clubid: 10016,
    abbreviation: 'MB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 106,
    name: 'Zuid-West',
    clubid: 40075,
    abbreviation: 'ZWB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 107,
    name: 'Rijkerack',
    clubid: 10065,
    abbreviation: 'RB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 108,
    name: 'Sportif',
    clubid: 40066,
    abbreviation: 'SV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 109,
    name: 'Torhout',
    clubid: 40011,
    abbreviation: 'TB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 110,
    name: 'Beerke',
    clubid: 10085,
    abbreviation: 'BtB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 111,
    name: 'Smash',
    clubid: 70013,
    abbreviation: 'SBL',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 112,
    name: 'Lubbinton',
    clubid: 20119,
    abbreviation: 'L',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 113,
    name: 'Gentse',
    clubid: 30009,
    abbreviation: 'GB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 114,
    name: 'BMC Peer',
    clubid: 70011,
    abbreviation: 'BBPV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 115,
    name: 'DENDERLEEUW BC',
    clubid: 30066,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 117,
    name: 'BLAUWPUT OMNISPORT VZW',
    clubid: 20105,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 118,
    name: 'Gitse Badmintonclub',
    clubid: 40004,
    abbreviation: 'Gitse BC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 119,
    name: 'BARLOKE',
    clubid: 40071,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 4,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 120,
    name: 'TURNHOUT BADMINTONCLUB',
    clubid: 10021,
    abbreviation: 'TBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 121,
    name: 'LEOBAD BC',
    clubid: 70005,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 122,
    name: 'KAMPENHOUT BC',
    clubid: 20064,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 1,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 123,
    name: 'Sporting Neerpelt Badminton Club',
    clubid: 70009,
    abbreviation: 'SNBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 6,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 124,
    name: 'Kraainem BC asbl',
    clubid: 23,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: null,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 7,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
];

export const cpClubsVvbbc = [
  {
    id: 30,
    name: 'Shuttles Opwijk',
    clubid: 20054,
    abbreviation: 'SOV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 31,
    name: 'Herne',
    clubid: 20063,
    abbreviation: 'BCH',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 32,
    name: 'Dijlevallei',
    clubid: 20006,
    abbreviation: 'DDV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 33,
    name: 'W&L BV',
    clubid: 20078,
    abbreviation: 'WLBV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 34,
    name: 'Halle',
    clubid: 20099,
    abbreviation: 'BH8',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 35,
    name: 'De Treffers',
    clubid: 20075,
    abbreviation: 'DT',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 36,
    name: 'Lubbinton',
    clubid: 20119,
    abbreviation: 'L',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 37,
    name: 'Tienen',
    clubid: 20004,
    abbreviation: 'TB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 38,
    name: 'Leeuwse',
    clubid: 20098,
    abbreviation: 'L',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 39,
    name: 'Brussels International',
    clubid: 20055,
    abbreviation: 'BIBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 40,
    name: 'Den Dijk',
    clubid: 20107,
    abbreviation: 'DD',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 41,
    name: 'Drop Merchtem',
    clubid: 20062,
    abbreviation: 'DMB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 42,
    name: "Nero's BC",
    clubid: 20095,
    abbreviation: 'NBHV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 43,
    name: 'Tots Keerbergen',
    clubid: 20073,
    abbreviation: 'BTK',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 44,
    name: 'Bamadi',
    clubid: 20089,
    abbreviation: 'B',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 45,
    name: 'Dropshot',
    clubid: 20109,
    abbreviation: 'DV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 46,
    name: 'Lob',
    clubid: 20072,
    abbreviation: 'L',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 47,
    name: 'De Voskes',
    clubid: 20112,
    abbreviation: 'DVB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 48,
    name: 'Kill Leuven',
    clubid: 20077,
    abbreviation: 'KL',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 49,
    name: 'BaZo',
    clubid: 20118,
    abbreviation: 'Zoutleeuw',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 50,
    name: 'Smashing Boutersem',
    clubid: 20204,
    abbreviation: 'SBB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 51,
    name: 'Pluimke Klop',
    clubid: 20096,
    abbreviation: 'PKB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 52,
    name: 'BC Wolvertem',
    clubid: 20016,
    abbreviation: 'BWM',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 53,
    name: 'Tervuren',
    clubid: 20097,
    abbreviation: 'TB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 54,
    name: 'Everbergse',
    clubid: 20074,
    abbreviation: 'EBC',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 55,
    name: 'Dilbeek',
    clubid: 20066,
    abbreviation: 'BD',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 56,
    name: 'Kampenhout',
    clubid: 20064,
    abbreviation: 'KB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 57,
    name: 'Bertemse',
    clubid: 20059,
    abbreviation: 'BB',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 58,
    name: 'Volano',
    clubid: 20090,
    abbreviation: 'BV',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: 19,
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 60,
    name: 'BLAUWPUT OMNISPORT VZW',
    clubid: 20105,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: '',
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 2,
    numcourts1: '',
    numcourts2: '',
    numcourts3: '',
    numcourts4: '',
    numcourts5: '',
    numcourts6: '',
    numcourts7: '',
    phoneprivate: '',
    faxprivate: '',
    location: '',
    externallink: '',
  },
  {
    id: 61,
    name: 'Bad79',
    clubid: 39,
    abbreviation: '',
    foreignid: '',
    contact: '',
    address: '',
    address2: '',
    address3: '',
    postalcode: '',
    city: '',
    state: '',
    country: '',
    phone: '',
    fax: '',
    mobile: '',
    email: '',
    website: '',
    district: 3,
  },
];

export const cpLocationsVvbbc = [
  {
    id: 36,
    name: 'sporthal Opwijk',
    foreignid: '',
    locationid: '',
    address: 'Heiveld 65',
    postalcode: 1745,
    city: '',
    phone: '0472769224',
    clubid: 30,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 37,
    name: 'DE HERNEKOUTER',
    foreignid: '',
    locationid: '',
    address: 'HERNEKOUTER 1',
    postalcode: 1540,
    city: 'HERNE',
    phone: '02/395.90.15',
    clubid: 31,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 38,
    name: 'Sportcomplex Kessel-Lo',
    foreignid: '',
    locationid: '',
    address: 'Stadionlaan 4',
    postalcode: 3010,
    city: 'Kessel-Lo',
    phone: null,
    clubid: 32,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 39,
    name: 'Sporthal Ivo Van Damme',
    foreignid: '',
    locationid: '',
    address: 'Overstraat 21',
    postalcode: 3020,
    city: 'Veltem-Beisem',
    phone: null,
    clubid: 33,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 40,
    name: 'Sportcentrum Bart Swings',
    foreignid: '',
    locationid: '',
    address: 'Kouterstraat 1',
    postalcode: 3020,
    city: 'Herent',
    phone: null,
    clubid: 33,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 41,
    name: 'Sportcomplex DE BRES',
    foreignid: '',
    locationid: '',
    address: 'M. SENCIESTRAAT 13',
    postalcode: 1500,
    city: 'HALLE',
    phone: '02/365.94.26',
    clubid: 34,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 42,
    name: 'Sporthal Den Heurk',
    foreignid: '',
    locationid: '',
    address: 'Heurkstraat 3',
    postalcode: 3090,
    city: 'Overijse',
    phone: '',
    clubid: 35,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 43,
    name: 'Sporthal Lubbeek',
    foreignid: '',
    locationid: '',
    address: 'Gellenberg 14',
    postalcode: 3210,
    city: 'Lubbeek',
    phone: '',
    clubid: 36,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 44,
    name: 'Houtemveld',
    foreignid: '',
    locationid: '',
    address: 'Sporthalstraat T',
    postalcode: 3300,
    city: 'Houtemveld',
    phone: '016/81.74.14',
    clubid: 37,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 45,
    name: 'A.J. BRAILLARD',
    foreignid: '',
    locationid: '',
    address: 'WANDELINGSTRAAT 52',
    postalcode: 1601,
    city: 'RUISBROEK',
    phone: '023775851',
    clubid: 38,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 46,
    name: 'SPORTHAL',
    foreignid: '',
    locationid: '',
    address: 'ASTRIDLAAN 85',
    postalcode: 1970,
    city: 'WEZEMBEEK OPPEM',
    phone: '',
    clubid: 39,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 47,
    name: 'DEN DIJK',
    foreignid: '',
    locationid: '',
    address: 'DIJKSTRAAT 1',
    postalcode: 3150,
    city: 'WESPELAAR',
    phone: '016/57.02.28',
    clubid: 40,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 48,
    name: 'DEN BOX',
    foreignid: '',
    locationid: '',
    address: 'Dijkstraat 1',
    postalcode: 3150,
    city: 'Haacht',
    phone: '016/57.02.28',
    clubid: 40,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 49,
    name: 'VZW Sport- en ontmoetingscentrum',
    foreignid: '',
    locationid: '',
    address: 'Dendermondestraat 25',
    postalcode: 1785,
    city: 'Merchtem',
    phone: '+3252371644',
    clubid: 41,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 50,
    name: 'Sport-en Jeugdcentrum Koldam',
    foreignid: '',
    locationid: '',
    address: 'KOLDAMSTRAAT 9A',
    postalcode: 1560,
    city: 'HOEILAART',
    phone: '02/657.97.26',
    clubid: 42,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 51,
    name: 'Sporthal K.A. Keerbergen',
    foreignid: '',
    locationid: '',
    address: 'Nachtegalendreef 7',
    postalcode: 3140,
    city: 'Keerbergen',
    phone: '',
    clubid: 43,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 52,
    name: 'SPORTHAL BOSVELD',
    foreignid: '',
    locationid: '',
    address: 'HEIRBAAN 10',
    postalcode: 1830,
    city: 'MACHELEN',
    phone: '',
    clubid: 44,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 53,
    name: 'Sportoase Ter Heide Rotselaar',
    foreignid: '',
    locationid: '',
    address: 'Vakenstraat 18',
    postalcode: 3110,
    city: 'Rotselaar',
    phone: '016/89.29.90',
    clubid: 45,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 54,
    name: 'SPORTHAL LONDERZEEL',
    foreignid: '',
    locationid: '',
    address: 'Lijsterstraat 1',
    postalcode: 1840,
    city: 'LONDERZEEL',
    phone: '',
    clubid: 46,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 55,
    name: "'Sporthal t Solveld",
    foreignid: '',
    locationid: '',
    address: 'Ralisweg 17',
    postalcode: 3390,
    city: 'Tielt Winge',
    phone: '016/63.95.69',
    clubid: 47,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 56,
    name: 'SPORTHAL UC Leuven Limburg',
    foreignid: '',
    locationid: '',
    address: 'KERSPELSTRAAT 70',
    postalcode: 3001,
    city: 'HEVERLEE',
    phone: '016/39.90.98',
    clubid: 48,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 57,
    name: 'sporthal De Passant',
    foreignid: '',
    locationid: '',
    address: 'Aen den Hoorn 12',
    postalcode: 3440,
    city: 'Zoutleeuw',
    phone: '011 94 90 51',
    clubid: 49,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 58,
    name: "Sport'o'droom",
    foreignid: '',
    locationid: '',
    address: 'Kerkomsesteenweg 49',
    postalcode: 3370,
    city: 'Boutersem',
    phone: '',
    clubid: 50,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 59,
    name: 'De Kronkel',
    foreignid: '',
    locationid: '',
    address: 'Gemeenteplein 2',
    postalcode: 3040,
    city: 'HULDENBERG',
    phone: '02/687.57.56',
    clubid: 51,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 60,
    name: 'Ter Dijle',
    foreignid: '',
    locationid: '',
    address: 'Leuvensebaan 299',
    postalcode: 3040,
    city: 'SINT-AGATHA-RODE',
    phone: null,
    clubid: 51,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 61,
    name: 'Sportschuur Wolvertem',
    foreignid: '',
    locationid: '',
    address: 'Populierenlaan 20',
    postalcode: 1861,
    city: 'Wolvertem',
    phone: '0479298327',
    clubid: 52,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 62,
    name: 'Diependal',
    foreignid: '',
    locationid: '',
    address: 'Lindeboomstraat 30',
    postalcode: 3080,
    city: 'Tervuren',
    phone: null,
    clubid: 53,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 63,
    name: 'GITO-Tervuren',
    foreignid: '',
    locationid: '',
    address: 'Pater Dupierreuxlaan 1B',
    postalcode: 3080,
    city: 'Tervuren',
    phone: '02 766 53 62',
    clubid: 53,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 64,
    name: 'COLOMBA KORTENBERG',
    foreignid: '',
    locationid: '',
    address: 'WIJNGAARDSTRAAT 1',
    postalcode: 3070,
    city: 'KORTENBERG',
    phone: '02/759.50.13',
    clubid: 54,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 65,
    name: 'TEN GAERDE',
    foreignid: '',
    locationid: '',
    address: 'J. MERTENSSTRAAT 27A',
    postalcode: 1702,
    city: 'GROOT BIJGAARDEN',
    phone: '02/463.30.49',
    clubid: 55,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 66,
    name: 'Sporthal De Zeype',
    foreignid: '',
    locationid: '',
    address: 'Zeypestraat 26',
    postalcode: 1910,
    city: 'Kampenhout',
    phone: '016/65.99.75',
    clubid: 56,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 67,
    name: 'SPORTZAAL BERTEM',
    foreignid: '',
    locationid: '',
    address: 'BOSSTRAAT 1',
    postalcode: 3060,
    city: 'BERTEM',
    phone: '016/49 97 71',
    clubid: 57,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 68,
    name: 'Sporthal Verona',
    foreignid: '',
    locationid: '',
    address: 'Kerstraat 58',
    postalcode: 3061,
    city: 'Bertem',
    phone: null,
    clubid: 57,
    locationnr: '',
    extrainfo: '',
    description: '',
    longitude: '',
    latitude: '',
    contact: '',
  },
  {
    id: 69,
    name: 'Sporthal Vertommen',
    foreignid: '',
    locationid: '',
    address: 'Grotewinkellaan 101',
    postalcode: 1853,
    city: 'Grimbergen',
    phone: '0476491783',
    clubid: 58,
  },
];

export type CpClub =
  | (typeof cpClubsVlaamse)[0]
  | (typeof cpClubsVvbbc)[0]
  | (typeof cpClubsLimburg)[0];
export type CpLocation =
  | (typeof cpLocationsVlaamse)[0]
  | (typeof cpLocationsVvbbc)[0]
  | (typeof cpLocationsLimburg)[0];
